// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package wire

import (
	rawjson "encoding/json"
)

// Defines values for ManifestEntityApply.
const (
	Replace ManifestEntityApply = "replace"
	Upsert  ManifestEntityApply = "upsert"
)

// Valid indicates whether the value is a known member of the ManifestEntityApply enum.
func (e ManifestEntityApply) Valid() bool {
	switch e {
	case Replace:
		return true
	case Upsert:
		return true
	default:
		return false
	}
}

// Defines values for ManifestEntityScope.
const (
	ManifestEntityScopeCompany ManifestEntityScope = "company"
	ManifestEntityScopeOutlet  ManifestEntityScope = "outlet"
)

// Valid indicates whether the value is a known member of the ManifestEntityScope enum.
func (e ManifestEntityScope) Valid() bool {
	switch e {
	case ManifestEntityScopeCompany:
		return true
	case ManifestEntityScopeOutlet:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	OrderStatusCancelled OrderStatus = "cancelled"
	OrderStatusPaid      OrderStatus = "paid"
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusPreparing OrderStatus = "preparing"
	OrderStatusReady     OrderStatus = "ready"
	OrderStatusRefunded  OrderStatus = "refunded"
	OrderStatusServed    OrderStatus = "served"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case OrderStatusCancelled:
		return true
	case OrderStatusPaid:
		return true
	case OrderStatusPending:
		return true
	case OrderStatusPreparing:
		return true
	case OrderStatusReady:
		return true
	case OrderStatusRefunded:
		return true
	case OrderStatusServed:
		return true
	default:
		return false
	}
}

// Defines values for PushResultCode.
const (
	Archived          PushResultCode = "archived"
	DependencyPending PushResultCode = "dependency_pending"
	Duplicate         PushResultCode = "duplicate"
	RecoveryRequired  PushResultCode = "recovery_required"
	RegisterBusy      PushResultCode = "register_busy"
	SchemaRejected    PushResultCode = "schema_rejected"
	ServerUnavailable PushResultCode = "server_unavailable"
	SessionClosed     PushResultCode = "session_closed"
	Settled           PushResultCode = "settled"
	StaleRevision     PushResultCode = "stale_revision"
	UnknownEntity     PushResultCode = "unknown_entity"
)

// Valid indicates whether the value is a known member of the PushResultCode enum.
func (e PushResultCode) Valid() bool {
	switch e {
	case Archived:
		return true
	case DependencyPending:
		return true
	case Duplicate:
		return true
	case RecoveryRequired:
		return true
	case RegisterBusy:
		return true
	case SchemaRejected:
		return true
	case ServerUnavailable:
		return true
	case SessionClosed:
		return true
	case Settled:
		return true
	case StaleRevision:
		return true
	case UnknownEntity:
		return true
	default:
		return false
	}
}

// Defines values for PushResultOutcome.
const (
	Applied    PushResultOutcome = "applied"
	Superseded PushResultOutcome = "superseded"
)

// Valid indicates whether the value is a known member of the PushResultOutcome enum.
func (e PushResultOutcome) Valid() bool {
	switch e {
	case Applied:
		return true
	case Superseded:
		return true
	default:
		return false
	}
}

// Defines values for PushResultStatus.
const (
	Accepted PushResultStatus = "accepted"
	Rejected PushResultStatus = "rejected"
	Retry    PushResultStatus = "retry"
)

// Valid indicates whether the value is a known member of the PushResultStatus enum.
func (e PushResultStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Rejected:
		return true
	case Retry:
		return true
	default:
		return false
	}
}

// Defines values for StockMovementReason.
const (
	Correction StockMovementReason = "correction"
	Count      StockMovementReason = "count"
	Opening    StockMovementReason = "opening"
	Received   StockMovementReason = "received"
	Sale       StockMovementReason = "sale"
	VoidReturn StockMovementReason = "voidReturn"
	Waste      StockMovementReason = "waste"
)

// Valid indicates whether the value is a known member of the StockMovementReason enum.
func (e StockMovementReason) Valid() bool {
	switch e {
	case Correction:
		return true
	case Count:
		return true
	case Opening:
		return true
	case Received:
		return true
	case Sale:
		return true
	case VoidReturn:
		return true
	case Waste:
		return true
	default:
		return false
	}
}

// Defines values for TableStatusEventStatus.
const (
	Available TableStatusEventStatus = "available"
	Occupied  TableStatusEventStatus = "occupied"
	Reserved  TableStatusEventStatus = "reserved"
)

// Valid indicates whether the value is a known member of the TableStatusEventStatus enum.
func (e TableStatusEventStatus) Valid() bool {
	switch e {
	case Available:
		return true
	case Occupied:
		return true
	case Reserved:
		return true
	default:
		return false
	}
}

// Defines values for TillHistoryPageScope.
const (
	TillHistoryPageScopeOutlet   TillHistoryPageScope = "outlet"
	TillHistoryPageScopeRegister TillHistoryPageScope = "register"
)

// Valid indicates whether the value is a known member of the TillHistoryPageScope enum.
func (e TillHistoryPageScope) Valid() bool {
	switch e {
	case TillHistoryPageScopeOutlet:
		return true
	case TillHistoryPageScopeRegister:
		return true
	default:
		return false
	}
}

// Defines values for TillRecoveryReconciliationBasis.
const (
	DeviceChecked     TillRecoveryReconciliationBasis = "device_checked"
	DeviceUnavailable TillRecoveryReconciliationBasis = "device_unavailable"
)

// Valid indicates whether the value is a known member of the TillRecoveryReconciliationBasis enum.
func (e TillRecoveryReconciliationBasis) Valid() bool {
	switch e {
	case DeviceChecked:
		return true
	case DeviceUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for TillRecoveryStatus.
const (
	RecoveryOpen       TillRecoveryStatus = "open"
	RecoveryReconciled TillRecoveryStatus = "reconciled"
)

// Valid indicates whether the value is a known member of the TillRecoveryStatus enum.
func (e TillRecoveryStatus) Valid() bool {
	switch e {
	case RecoveryOpen:
		return true
	case RecoveryReconciled:
		return true
	default:
		return false
	}
}

// Defines values for TillRecoveryItemStatus.
const (
	RecoveryItemAccepted  TillRecoveryItemStatus = "accepted"
	RecoveryItemDiscarded TillRecoveryItemStatus = "discarded"
	RecoveryItemPending   TillRecoveryItemStatus = "pending"
)

// Valid indicates whether the value is a known member of the TillRecoveryItemStatus enum.
func (e TillRecoveryItemStatus) Valid() bool {
	switch e {
	case RecoveryItemAccepted:
		return true
	case RecoveryItemDiscarded:
		return true
	case RecoveryItemPending:
		return true
	default:
		return false
	}
}

// Defines values for ReportPeriod.
const (
	ReportPeriodCustom    ReportPeriod = "custom"
	ReportPeriodLast7     ReportPeriod = "last7"
	ReportPeriodMonth     ReportPeriod = "month"
	ReportPeriodToday     ReportPeriod = "today"
	ReportPeriodYesterday ReportPeriod = "yesterday"
)

// Valid indicates whether the value is a known member of the ReportPeriod enum.
func (e ReportPeriod) Valid() bool {
	switch e {
	case ReportPeriodCustom:
		return true
	case ReportPeriodLast7:
		return true
	case ReportPeriodMonth:
		return true
	case ReportPeriodToday:
		return true
	case ReportPeriodYesterday:
		return true
	default:
		return false
	}
}

// Defines values for TillOrderHistoryParamsScope.
const (
	TillOrderHistoryParamsScopeOutlet   TillOrderHistoryParamsScope = "outlet"
	TillOrderHistoryParamsScopeRegister TillOrderHistoryParamsScope = "register"
)

// Valid indicates whether the value is a known member of the TillOrderHistoryParamsScope enum.
func (e TillOrderHistoryParamsScope) Valid() bool {
	switch e {
	case TillOrderHistoryParamsScopeOutlet:
		return true
	case TillOrderHistoryParamsScopeRegister:
		return true
	default:
		return false
	}
}

// Defines values for TillOrderHistoryParamsStatus.
const (
	TillOrderHistoryParamsStatusCancelled TillOrderHistoryParamsStatus = "cancelled"
	TillOrderHistoryParamsStatusPaid      TillOrderHistoryParamsStatus = "paid"
	TillOrderHistoryParamsStatusPending   TillOrderHistoryParamsStatus = "pending"
	TillOrderHistoryParamsStatusPreparing TillOrderHistoryParamsStatus = "preparing"
	TillOrderHistoryParamsStatusReady     TillOrderHistoryParamsStatus = "ready"
	TillOrderHistoryParamsStatusRefunded  TillOrderHistoryParamsStatus = "refunded"
	TillOrderHistoryParamsStatusSales     TillOrderHistoryParamsStatus = "sales"
	TillOrderHistoryParamsStatusServed    TillOrderHistoryParamsStatus = "served"
)

// Valid indicates whether the value is a known member of the TillOrderHistoryParamsStatus enum.
func (e TillOrderHistoryParamsStatus) Valid() bool {
	switch e {
	case TillOrderHistoryParamsStatusCancelled:
		return true
	case TillOrderHistoryParamsStatusPaid:
		return true
	case TillOrderHistoryParamsStatusPending:
		return true
	case TillOrderHistoryParamsStatusPreparing:
		return true
	case TillOrderHistoryParamsStatusReady:
		return true
	case TillOrderHistoryParamsStatusRefunded:
		return true
	case TillOrderHistoryParamsStatusSales:
		return true
	case TillOrderHistoryParamsStatusServed:
		return true
	default:
		return false
	}
}

// Defines values for TillReportSalesParamsPeriod.
const (
	TillReportSalesParamsPeriodCustom    TillReportSalesParamsPeriod = "custom"
	TillReportSalesParamsPeriodLast7     TillReportSalesParamsPeriod = "last7"
	TillReportSalesParamsPeriodMonth     TillReportSalesParamsPeriod = "month"
	TillReportSalesParamsPeriodToday     TillReportSalesParamsPeriod = "today"
	TillReportSalesParamsPeriodYesterday TillReportSalesParamsPeriod = "yesterday"
)

// Valid indicates whether the value is a known member of the TillReportSalesParamsPeriod enum.
func (e TillReportSalesParamsPeriod) Valid() bool {
	switch e {
	case TillReportSalesParamsPeriodCustom:
		return true
	case TillReportSalesParamsPeriodLast7:
		return true
	case TillReportSalesParamsPeriodMonth:
		return true
	case TillReportSalesParamsPeriodToday:
		return true
	case TillReportSalesParamsPeriodYesterday:
		return true
	default:
		return false
	}
}

// Defines values for TillReportSummaryParamsPeriod.
const (
	TillReportSummaryParamsPeriodCustom    TillReportSummaryParamsPeriod = "custom"
	TillReportSummaryParamsPeriodLast7     TillReportSummaryParamsPeriod = "last7"
	TillReportSummaryParamsPeriodMonth     TillReportSummaryParamsPeriod = "month"
	TillReportSummaryParamsPeriodToday     TillReportSummaryParamsPeriod = "today"
	TillReportSummaryParamsPeriodYesterday TillReportSummaryParamsPeriod = "yesterday"
)

// Valid indicates whether the value is a known member of the TillReportSummaryParamsPeriod enum.
func (e TillReportSummaryParamsPeriod) Valid() bool {
	switch e {
	case TillReportSummaryParamsPeriodCustom:
		return true
	case TillReportSummaryParamsPeriodLast7:
		return true
	case TillReportSummaryParamsPeriodMonth:
		return true
	case TillReportSummaryParamsPeriodToday:
		return true
	case TillReportSummaryParamsPeriodYesterday:
		return true
	default:
		return false
	}
}

// ActivateRequest defines model for ActivateRequest.
type ActivateRequest struct {
	Code       string  `json:"code"`
	DeviceUuid ID      `json:"device_uuid"`
	Label      *string `json:"label,omitempty"`
	Platform   *string `json:"platform,omitempty"`
}

// ActivateResponse defines model for ActivateResponse.
type ActivateResponse struct {
	Data struct {
		Device           Device   `json:"device"`
		Outlet           Outlet   `json:"outlet"`
		PosRegister      Register `json:"pos_register"`
		Tenant           Tenant   `json:"tenant"`
		Token            string   `json:"token"`
		TokenExpiresAtMs Millis   `json:"token_expires_at_ms"`
	} `json:"data"`
}

// Binding defines model for Binding.
type Binding struct {
	Device      Device   `json:"device"`
	Outlet      Outlet   `json:"outlet"`
	PosRegister Register `json:"pos_register"`
	Tenant      Tenant   `json:"tenant"`
}

// CategoryRow defines model for CategoryRow.
type CategoryRow struct {
	DeletedAtMs *int64  `json:"deleted_at_ms"`
	IconKey     *string `json:"icon_key"`
	Id          string  `json:"id"`
	IsPopular   bool    `json:"is_popular"`
	Name        string  `json:"name"`
	SortOrder   int64   `json:"sort_order"`
	SyncSeq     int64   `json:"sync_seq"`
}

// Changes defines model for Changes.
type Changes struct {
	Cursors        map[string]int64 `json:"cursors"`
	DeviceRevision Millis           `json:"device_revision"`
	NextPollMs     int64            `json:"next_poll_ms"`
	ServerTimeMs   Millis           `json:"server_time_ms"`
}

// Device defines model for Device.
type Device struct {
	DeviceUuid ID      `json:"device_uuid"`
	Id         ID      `json:"id"`
	Label      *string `json:"label"`
	Platform   *string `json:"platform"`
}

// EmployeeRow defines model for EmployeeRow.
type EmployeeRow struct {
	Active      bool    `json:"active"`
	DeletedAtMs *int64  `json:"deleted_at_ms"`
	Id          string  `json:"id"`
	Name        string  `json:"name"`
	PinHash     *string `json:"pin_hash"`
	Role        string  `json:"role"`
	SortOrder   int64   `json:"sort_order"`
	SyncSeq     int64   `json:"sync_seq"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Cache    string `json:"cache"`
	Database string `json:"database"`
	Service  string `json:"service"`
	Status   string `json:"status"`
}

// ID defines model for ID.
type ID = string

// Manifest defines model for Manifest.
type Manifest struct {
	Entities      []ManifestEntity `json:"entities"`
	SchemaVersion int              `json:"schema_version"`
}

// ManifestEntity defines model for ManifestEntity.
type ManifestEntity struct {
	Apply     ManifestEntityApply `json:"apply"`
	DependsOn []string            `json:"depends_on"`
	Key       []string            `json:"key"`
	Name      string              `json:"name"`
	Pull      bool                `json:"pull"`
	Push      bool                `json:"push"`
	Scope     ManifestEntityScope `json:"scope"`
}

// ManifestEntityApply defines model for ManifestEntity.Apply.
type ManifestEntityApply string

// ManifestEntityScope defines model for ManifestEntity.Scope.
type ManifestEntityScope string

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Data Binding `json:"data"`
}

// Millis defines model for Millis.
type Millis = int64

// ModifierGroupRow defines model for ModifierGroupRow.
type ModifierGroupRow struct {
	Active        bool   `json:"active"`
	DeletedAtMs   *int64 `json:"deleted_at_ms"`
	Id            string `json:"id"`
	MaxSelect     *int64 `json:"max_select"`
	Name          string `json:"name"`
	Required      bool   `json:"required"`
	SelectionType string `json:"selection_type"`
	SortOrder     int64  `json:"sort_order"`
	SyncSeq       int64  `json:"sync_seq"`
}

// ModifierOptionRow defines model for ModifierOptionRow.
type ModifierOptionRow struct {
	Active      bool   `json:"active"`
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	GroupId     string `json:"group_id"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	PriceDelta  int64  `json:"price_delta"`
	SortOrder   int64  `json:"sort_order"`
	SyncSeq     int64  `json:"sync_seq"`
}

// Money defines model for Money.
type Money = int64

// Name defines model for Name.
type Name = string

// Order defines model for Order.
type Order struct {
	AmountPaid          Money       `json:"amount_paid"`
	AuthorizedBy        *string     `json:"authorized_by,omitempty"`
	BusinessDate        string      `json:"business_date"`
	CashierId           *string     `json:"cashier_id,omitempty"`
	CashierName         Name        `json:"cashier_name"`
	CustomerName        *string     `json:"customer_name,omitempty"`
	Discount            Money       `json:"discount"`
	Id                  UUID        `json:"id"`
	Items               []OrderItem `json:"items"`
	Note                *string     `json:"note,omitempty"`
	Number              string      `json:"number"`
	OutletName          *string     `json:"outlet_name,omitempty"`
	PaymentMethod       string      `json:"payment_method"`
	Pb1Rate             *float64    `json:"pb1_rate,omitempty"`
	PlacedAtMs          Millis      `json:"placed_at_ms"`
	PosName             *string     `json:"pos_name,omitempty"`
	PosSessionId        UUID        `json:"pos_session_id"`
	PromoName           *string     `json:"promo_name,omitempty"`
	RefundedAmount      *int64      `json:"refunded_amount,omitempty"`
	Revision            int64       `json:"revision"`
	ServerTimeDeltaMs   *int64      `json:"server_time_delta_ms,omitempty"`
	ServiceChargeAmount Money       `json:"service_charge_amount"`
	ServiceChargeRate   *float64    `json:"service_charge_rate,omitempty"`
	Status              OrderStatus `json:"status"`

	// StockMovements Complete immutable sale and optional return movements committed atomically with this receipt.
	StockMovements *[]StockMovement `json:"stock_movements,omitempty"`
	Subtotal       Money            `json:"subtotal"`
	TableId        *string          `json:"table_id,omitempty"`
	TableName      *string          `json:"table_name,omitempty"`
	Tax            Money            `json:"tax"`
	Total          Money            `json:"total"`
	Type           string           `json:"type"`
	VoidReason     *string          `json:"void_reason,omitempty"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// OrderItem unit_price is the final per-unit snapshot including variant/modifier deltas; never add modifier price_delta to it again. subtotal equals sum(unit_price * quantity).
type OrderItem struct {
	CategoryId   *string             `json:"category_id,omitempty"`
	CategoryName *string             `json:"category_name,omitempty"`
	Id           UUID                `json:"id"`
	Modifiers    []OrderItemModifier `json:"modifiers"`
	Note         *string             `json:"note,omitempty"`
	ProductId    *string             `json:"product_id,omitempty"`
	ProductName  Name                `json:"product_name"`
	Quantity     int                 `json:"quantity"`
	UnitCost     *int64              `json:"unit_cost,omitempty"`
	UnitPrice    Money               `json:"unit_price"`
	VariantName  *string             `json:"variant_name,omitempty"`
}

// OrderItemModifier defines model for OrderItemModifier.
type OrderItemModifier struct {
	GroupName  Name  `json:"group_name"`
	Id         UUID  `json:"id"`
	OptionName Name  `json:"option_name"`
	PriceDelta int64 `json:"price_delta"`
	SortOrder  int   `json:"sort_order"`
}

// Outlet defines model for Outlet.
type Outlet struct {
	Address *string `json:"address"`
	Id      ID      `json:"id"`
	Name    string  `json:"name"`
	Phone   *string `json:"phone"`
}

// OutletRow defines model for OutletRow.
type OutletRow struct {
	Active      bool    `json:"active"`
	Address     *string `json:"address"`
	DeletedAtMs *int64  `json:"deleted_at_ms"`
	Id          string  `json:"id"`
	Name        string  `json:"name"`
	SortOrder   int64   `json:"sort_order"`
	SyncSeq     int64   `json:"sync_seq"`
}

// OutletStockRow defines model for OutletStockRow.
type OutletStockRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	OutletId    string `json:"outlet_id"`
	ProductId   string `json:"product_id"`
	QtyOnHand   int64  `json:"qty_on_hand"`
	SyncSeq     int64  `json:"sync_seq"`
}

// ProductModifierGroupRow defines model for ProductModifierGroupRow.
type ProductModifierGroupRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	GroupId     string `json:"group_id"`
	ProductId   string `json:"product_id"`
	SyncSeq     int64  `json:"sync_seq"`
}

// ProductModifierOptionRow defines model for ProductModifierOptionRow.
type ProductModifierOptionRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	IsDefault   bool   `json:"is_default"`
	OptionId    string `json:"option_id"`
	ProductId   string `json:"product_id"`
	SyncSeq     int64  `json:"sync_seq"`
}

// ProductRow defines model for ProductRow.
type ProductRow struct {
	Available   bool     `json:"available"`
	CategoryId  *string  `json:"category_id"`
	Cost        *int64   `json:"cost"`
	DeletedAtMs *int64   `json:"deleted_at_ms"`
	Description *string  `json:"description"`
	IconKey     *string  `json:"icon_key"`
	Id          string   `json:"id"`
	ImageUrl    *string  `json:"image_url"`
	IsPopular   bool     `json:"is_popular"`
	Name        string   `json:"name"`
	Price       int64    `json:"price"`
	Sku         *string  `json:"sku"`
	SortOrder   int64    `json:"sort_order"`
	SyncSeq     int64    `json:"sync_seq"`
	TaxRate     *float32 `json:"tax_rate"`
}

// PromoOutletRow defines model for PromoOutletRow.
type PromoOutletRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	OutletId    string `json:"outlet_id"`
	PromoId     string `json:"promo_id"`
	SyncSeq     int64  `json:"sync_seq"`
}

// PromoRow defines model for PromoRow.
type PromoRow struct {
	Active      bool   `json:"active"`
	AllOutlets  bool   `json:"all_outlets"`
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	Id          string `json:"id"`
	Kind        string `json:"kind"`
	MinSpend    int64  `json:"min_spend"`
	Name        string `json:"name"`
	SortOrder   int64  `json:"sort_order"`
	SyncSeq     int64  `json:"sync_seq"`
	Value       int64  `json:"value"`
}

// PullPage defines model for PullPage.
type PullPage struct {
	Entity        string               `json:"entity"`
	HasMore       bool                 `json:"has_more"`
	NextSeq       int64                `json:"next_seq"`
	Rows          []rawjson.RawMessage `json:"rows"`
	SchemaVersion int                  `json:"schema_version"`
}

// PushBatch defines model for PushBatch.
type PushBatch struct {
	Entity string               `json:"entity"`
	Rows   []rawjson.RawMessage `json:"rows"`
}

// PushRequest defines model for PushRequest.
type PushRequest struct {
	Batches []PushBatch `json:"batches"`
}

// PushResponse defines model for PushResponse.
type PushResponse struct {
	Results      []PushResult `json:"results"`
	ServerTimeMs Millis       `json:"server_time_ms"`
}

// PushResult defines model for PushResult.
type PushResult struct {
	// BalanceAfter For an accepted stock movement, the outlet's quantity immediately after it (a count's computed delta included).
	BalanceAfter       *int64          `json:"balance_after,omitempty"`
	BatchIndex         int             `json:"batch_index"`
	BusinessDate       *string         `json:"business_date,omitempty"`
	Code               *PushResultCode `json:"code,omitempty"`
	Entity             string          `json:"entity"`
	HolderEmployeeName *string         `json:"holder_employee_name,omitempty"`
	HolderSessionId    *string         `json:"holder_session_id,omitempty"`
	Id                 *string         `json:"id,omitempty"`
	Inserted           *bool           `json:"inserted,omitempty"`
	Message            *string         `json:"message,omitempty"`

	// Outcome For an accepted table status event, whether the table took its status (applied) or kept a later change by another till (superseded).
	Outcome    *PushResultOutcome `json:"outcome,omitempty"`
	RecoveryId *UUID              `json:"recovery_id,omitempty"`
	Revision   *int64             `json:"revision,omitempty"`
	RowIndex   int                `json:"row_index"`
	Status     PushResultStatus   `json:"status"`

	// StatusSeq For an accepted table status event, the table_status sync_seq it was recorded at. A snapshot at or past it already reflects the event.
	StatusSeq *int64 `json:"status_seq,omitempty"`

	// StockSeq For an accepted stock movement, the outlet_stock sync_seq of its product after the movement was applied. A snapshot at or past it already includes the movement.
	StockSeq *int64 `json:"stock_seq,omitempty"`
}

// PushResultCode defines model for PushResult.Code.
type PushResultCode string

// PushResultOutcome For an accepted table status event, whether the table took its status (applied) or kept a later change by another till (superseded).
type PushResultOutcome string

// PushResultStatus defines model for PushResult.Status.
type PushResultStatus string

// Register defines model for Register.
type Register struct {
	Id           ID     `json:"id"`
	Name         string `json:"name"`
	OutletId     ID     `json:"outlet_id"`
	TableService bool   `json:"table_service"`
}

// RegisterRow defines model for RegisterRow.
type RegisterRow struct {
	Active       bool   `json:"active"`
	DeletedAtMs  *int64 `json:"deleted_at_ms"`
	Id           string `json:"id"`
	Name         string `json:"name"`
	OutletId     string `json:"outlet_id"`
	SortOrder    int64  `json:"sort_order"`
	SyncSeq      int64  `json:"sync_seq"`
	TableService bool   `json:"table_service"`
}

// ServerTime defines model for ServerTime.
type ServerTime struct {
	ServerTimeMs Millis `json:"server_time_ms"`
}

// Session defines model for Session.
type Session struct {
	ClosedAtMs   *int64  `json:"closed_at_ms,omitempty"`
	ClosedById   *string `json:"closed_by_id,omitempty"`
	ClosedByName *string `json:"closed_by_name,omitempty"`
	CountedCash  *int64  `json:"counted_cash,omitempty"`
	EmployeeId   *string `json:"employee_id,omitempty"`
	EmployeeName Name    `json:"employee_name"`
	ExpectedCash *int64  `json:"expected_cash,omitempty"`
	Id           UUID    `json:"id"`
	Note         *string `json:"note,omitempty"`
	OpenedAtMs   Millis  `json:"opened_at_ms"`
	OpeningCash  Money   `json:"opening_cash"`

	// OrderCount Required when closing an online-claimed session. Number of durably recorded receipts in the drawer.
	OrderCount *int64  `json:"order_count,omitempty"`
	OutletName *string `json:"outlet_name,omitempty"`
	PosName    *string `json:"pos_name,omitempty"`
	Revision   int64   `json:"revision"`
}

// StockMovement One immutable ledger movement, applied at the token's outlet. delta_qty
// is signed: sale and waste negative, voidReturn and received positive,
// correction and opening non-zero. A count carries counted_qty; the server
// replaces its delta_qty with counted_qty minus the server's current
// quantity (server wins). An exact retry, including one at a newer
// revision, is accepted with the originally recorded result.
type StockMovement struct {
	BasisSeq     *int64              `json:"basis_seq,omitempty"`
	CountedQty   *int64              `json:"counted_qty,omitempty"`
	DeltaQty     int64               `json:"delta_qty"`
	EmployeeId   *string             `json:"employee_id,omitempty"`
	EmployeeName string              `json:"employee_name"`
	Id           UUID                `json:"id"`
	Note         *string             `json:"note,omitempty"`
	OccurredAtMs Millis              `json:"occurred_at_ms"`
	ProductId    UUID                `json:"product_id"`
	ProductName  string              `json:"product_name"`
	Reason       StockMovementReason `json:"reason"`
	Revision     int64               `json:"revision"`
}

// StockMovementReason defines model for StockMovement.Reason.
type StockMovementReason string

// StockMovementRow defines model for StockMovementRow.
type StockMovementRow struct {
	BalanceAfter int64   `json:"balance_after"`
	CountedQty   *int64  `json:"counted_qty"`
	DeletedAtMs  *int64  `json:"deleted_at_ms"`
	DeltaQty     int64   `json:"delta_qty"`
	EmployeeName string  `json:"employee_name"`
	Id           string  `json:"id"`
	Note         *string `json:"note"`
	OccurredAtMs int64   `json:"occurred_at_ms"`
	OutletId     string  `json:"outlet_id"`
	ProductId    string  `json:"product_id"`
	ProductName  string  `json:"product_name"`
	Reason       string  `json:"reason"`
	Source       string  `json:"source"`
	StockSeq     int64   `json:"stock_seq"`
	SyncSeq      int64   `json:"sync_seq"`
}

// TableRow defines model for TableRow.
type TableRow struct {
	Active      bool   `json:"active"`
	Area        string `json:"area"`
	Capacity    int64  `json:"capacity"`
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	OutletId    string `json:"outlet_id"`
	PosX        *int64 `json:"pos_x"`
	PosY        *int64 `json:"pos_y"`
	SortOrder   int64  `json:"sort_order"`
	SyncSeq     int64  `json:"sync_seq"`
}

// TableStatusEvent One immutable change of a table's live status, applied at the token's
// outlet. basis_seq is the table_status sync_seq the till had pulled for
// the table when it made the change (0 if it had none). An event made
// against the current sequence, or following the same device's own latest
// write, applies. One that raced another till's write is applied or
// superseded by occurred_at_ms (the event id breaks a tie) and marks the
// table contested; the next uncontested change clears the mark. An exact
// retry, including one at a newer revision, is accepted with the
// originally recorded result. client_seq orders this device's events even
// across clock corrections or reordered delivery; an older number is
// recorded as superseded. Tills number events max(previous + 1, wall-clock
// milliseconds), so a store reinstalled under the same device never reuses
// a number. A basis_seq ahead of the current table projection is refused.
type TableStatusEvent struct {
	BasisSeq int64 `json:"basis_seq"`

	// ClientSeq Monotonic per-device per-table event number, persisted offline. Older events never undo a later event from the same device.
	ClientSeq    int64                  `json:"client_seq"`
	EmployeeName string                 `json:"employee_name"`
	Id           UUID                   `json:"id"`
	OccurredAtMs Millis                 `json:"occurred_at_ms"`
	Revision     int64                  `json:"revision"`
	Status       TableStatusEventStatus `json:"status"`
	TableId      UUID                   `json:"table_id"`
}

// TableStatusEventStatus defines model for TableStatusEvent.Status.
type TableStatusEventStatus string

// TableStatusRow defines model for TableStatusRow.
type TableStatusRow struct {
	Contested    bool   `json:"contested"`
	DeletedAtMs  *int64 `json:"deleted_at_ms"`
	EmployeeName string `json:"employee_name"`
	OccurredAtMs int64  `json:"occurred_at_ms"`
	OutletId     string `json:"outlet_id"`
	Status       string `json:"status"`
	SyncSeq      int64  `json:"sync_seq"`
	TableId      string `json:"table_id"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	Id   ID     `json:"id"`
	Name string `json:"name"`
}

// TillCurrentResponse defines model for TillCurrentResponse.
type TillCurrentResponse struct {
	Data     *TillSessionData     `json:"data"`
	Recovery *TillRecoveryPointer `json:"recovery,omitempty"`
}

// TillHandoverRequest defines model for TillHandoverRequest.
type TillHandoverRequest struct {
	Id UUID `json:"id"`
}

// TillHistoryPage defines model for TillHistoryPage.
type TillHistoryPage struct {
	From string                   `json:"from"`
	Next string                   `json:"next"`
	Rows []map[string]interface{} `json:"rows"`

	// Scope What the server applied, which may be narrower than what was asked for.
	Scope        TillHistoryPageScope `json:"scope"`
	ServerTimeMs Millis               `json:"server_time_ms"`
	To           string               `json:"to"`
}

// TillHistoryPageScope What the server applied, which may be narrower than what was asked for.
type TillHistoryPageScope string

// TillHistoryResponse defines model for TillHistoryResponse.
type TillHistoryResponse struct {
	Data TillHistoryPage `json:"data"`
}

// TillLoginData defines model for TillLoginData.
type TillLoginData struct {
	ExpiresAtMs Millis `json:"expires_at_ms"`
	Token       string `json:"token"`
}

// TillLoginRequest defines model for TillLoginRequest.
type TillLoginRequest struct {
	EmployeeId UUID   `json:"employee_id"`
	Pin        string `json:"pin"`
}

// TillLoginResponse defines model for TillLoginResponse.
type TillLoginResponse struct {
	Data TillLoginData `json:"data"`
}

// TillRecovery defines model for TillRecovery.
type TillRecovery struct {
	ForcedAtMs          Millis                           `json:"forced_at_ms"`
	Id                  UUID                             `json:"id"`
	Items               []TillRecoveryItem               `json:"items"`
	ReconciliationBasis *TillRecoveryReconciliationBasis `json:"reconciliation_basis,omitempty"`
	SessionId           UUID                             `json:"session_id"`
	Status              TillRecoveryStatus               `json:"status"`
}

// TillRecoveryReconciliationBasis defines model for TillRecovery.ReconciliationBasis.
type TillRecoveryReconciliationBasis string

// TillRecoveryStatus defines model for TillRecovery.Status.
type TillRecoveryStatus string

// TillRecoveryItem defines model for TillRecoveryItem.
type TillRecoveryItem struct {
	CreatedAtMs    Millis                 `json:"created_at_ms"`
	DecidedAtMs    *Millis                `json:"decided_at_ms,omitempty"`
	DecisionReason *string                `json:"decision_reason,omitempty"`
	Entity         string                 `json:"entity"`
	EntityId       UUID                   `json:"entity_id"`
	Id             UUID                   `json:"id"`
	Revision       int64                  `json:"revision"`
	Status         TillRecoveryItemStatus `json:"status"`
}

// TillRecoveryItemStatus defines model for TillRecoveryItem.Status.
type TillRecoveryItemStatus string

// TillRecoveryPointer defines model for TillRecoveryPointer.
type TillRecoveryPointer struct {
	ForcedAtMs Millis `json:"forced_at_ms"`
	Id         UUID   `json:"id"`
	SessionId  UUID   `json:"session_id"`
}

// TillRecoveryResponse defines model for TillRecoveryResponse.
type TillRecoveryResponse struct {
	Data TillRecovery `json:"data"`
}

// TillReport defines model for TillReport.
type TillReport struct {
	Adjustments *[]map[string]interface{} `json:"adjustments,omitempty"`

	// AnomalyCount Receipts whose own arithmetic does not close. Reported, never repaired.
	AnomalyCount        *int64                    `json:"anomaly_count,omitempty"`
	ByCashier           *[]map[string]interface{} `json:"by_cashier,omitempty"`
	ByCategory          *[]map[string]interface{} `json:"by_category,omitempty"`
	ByDay               *[]map[string]interface{} `json:"by_day,omitempty"`
	ByHour              *[]map[string]interface{} `json:"by_hour,omitempty"`
	ByOutlet            *[]map[string]interface{} `json:"by_outlet,omitempty"`
	ByPayment           *[]map[string]interface{} `json:"by_payment,omitempty"`
	ByProduct           *[]map[string]interface{} `json:"by_product,omitempty"`
	ByProductInCategory *[]map[string]interface{} `json:"by_product_in_category,omitempty"`

	// ByWeekday Derived from the business date, so a sale after midnight belongs to its trading day. weekday is 0 for Sunday.
	ByWeekday *[]map[string]interface{} `json:"by_weekday,omitempty"`

	// CalculationVersion Which rules produced these figures. 2 is the Fase 1 waterfall.
	CalculationVersion int `json:"calculation_version"`

	// ComputedAtMs Null when the range holds no computed rollup at all.
	ComputedAtMs *int64 `json:"computed_at_ms,omitempty"`

	// Incomplete True while some day in range is still computed under the old rules; the waterfall columns are not final.
	Incomplete bool `json:"incomplete"`

	// PendingSlices Day-outlet slices in range with changes not yet rolled up.
	PendingSlices int64            `json:"pending_slices"`
	Period        TillReportPeriod `json:"period"`

	// Profit Present only on /till/reports/sales. margin is null when there are no net sales to divide by.
	Profit *TillReportProfit `json:"profit,omitempty"`

	// Sales The waterfall, read top to bottom. net_sales = gross_sales - discounts - sales_returns; revenue = net_sales + tax + service_charge. gross_sales includes a receipt that was later refunded, and sales_returns takes it out again, so a refund is visible rather than the day silently shrinking. refunded_amount is the money handed back, which includes tax and is therefore not the same number as sales_returns. cancelled_amount is shown separately and is never subtracted from the waterfall.
	Sales        TillReportSales `json:"sales"`
	Scope        TillReportScope `json:"scope"`
	ServerTimeMs Millis          `json:"server_time_ms"`
	Timezone     string          `json:"timezone"`
}

// TillReportPeriod defines model for TillReportPeriod.
type TillReportPeriod struct {
	Days int    `json:"days"`
	From string `json:"from"`
	To   string `json:"to"`
}

// TillReportProfit Present only on /till/reports/sales. margin is null when there are no net sales to divide by.
type TillReportProfit struct {
	CostCoverage float64  `json:"cost_coverage"`
	CostOfGoods  Money    `json:"cost_of_goods"`
	GrossProfit  int64    `json:"gross_profit"`
	Margin       *float64 `json:"margin,omitempty"`
}

// TillReportResponse defines model for TillReportResponse.
type TillReportResponse struct {
	Data TillReport `json:"data"`
}

// TillReportSales The waterfall, read top to bottom. net_sales = gross_sales - discounts - sales_returns; revenue = net_sales + tax + service_charge. gross_sales includes a receipt that was later refunded, and sales_returns takes it out again, so a refund is visible rather than the day silently shrinking. refunded_amount is the money handed back, which includes tax and is therefore not the same number as sales_returns. cancelled_amount is shown separately and is never subtracted from the waterfall.
type TillReportSales struct {
	AverageSale     Money  `json:"average_sale"`
	CancelledAmount *Money `json:"cancelled_amount,omitempty"`
	CancelledCount  *int64 `json:"cancelled_count,omitempty"`
	Discounted      *int64 `json:"discounted,omitempty"`
	Discounts       Money  `json:"discounts"`
	GrossSales      Money  `json:"gross_sales"`
	ItemsSold       int64  `json:"items_sold"`
	NetSales        Money  `json:"net_sales"`
	OrderCount      int64  `json:"order_count"`
	RefundedAmount  *Money `json:"refunded_amount,omitempty"`
	RefundedCount   *int64 `json:"refunded_count,omitempty"`
	Revenue         Money  `json:"revenue"`
	SalesReturns    Money  `json:"sales_returns"`
	ServiceCharge   Money  `json:"service_charge"`
	Tax             Money  `json:"tax"`
}

// TillReportScope defines model for TillReportScope.
type TillReportScope struct {
	AllOutlets bool   `json:"all_outlets"`
	OutletId   string `json:"outlet_id"`
	OutletName string `json:"outlet_name"`
}

// TillSessionData defines model for TillSessionData.
type TillSessionData struct {
	CurrentEmployeeId *UUID   `json:"current_employee_id,omitempty"`
	ReceiptEnd        int64   `json:"receipt_end"`
	ReceiptStart      int64   `json:"receipt_start"`
	Session           Session `json:"session"`
}

// TillSessionResponse defines model for TillSessionResponse.
type TillSessionResponse struct {
	Data TillSessionData `json:"data"`
}

// UUID defines model for UUID.
type UUID = string

// VariantRow defines model for VariantRow.
type VariantRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	PriceDelta  int64  `json:"price_delta"`
	ProductId   string `json:"product_id"`
	SortOrder   int64  `json:"sort_order"`
	SyncSeq     int64  `json:"sync_seq"`
}

// CashierToken defines model for CashierToken.
type CashierToken = string

// ReportFrom defines model for ReportFrom.
type ReportFrom = string

// ReportOutlet defines model for ReportOutlet.
type ReportOutlet = string

// ReportPeriod defines model for ReportPeriod.
type ReportPeriod string

// ReportTo defines model for ReportTo.
type ReportTo = string

// SchemaVersion defines model for SchemaVersion.
type SchemaVersion = int

// Error defines model for Error.
type Error = ErrorResponse

// GetChangesParams defines parameters for GetChanges.
type GetChangesParams struct {
	// XSchemaVersion Missing/obsolete returns 409 device_schema_outdated; invalid returns 400.
	XSchemaVersion SchemaVersion `json:"X-Schema-Version"`
}

// GetManifestParams defines parameters for GetManifest.
type GetManifestParams struct {
	// XSchemaVersion Missing/obsolete returns 409 device_schema_outdated; invalid returns 400.
	XSchemaVersion SchemaVersion `json:"X-Schema-Version"`
}

// PullChangesParams defines parameters for PullChanges.
type PullChangesParams struct {
	Entity   string `form:"entity" json:"entity"`
	AfterSeq *int64 `form:"after_seq,omitempty" json:"after_seq,omitempty"`
	Limit    *int   `form:"limit,omitempty" json:"limit,omitempty"`

	// XSchemaVersion Missing/obsolete returns 409 device_schema_outdated; invalid returns 400.
	XSchemaVersion SchemaVersion `json:"X-Schema-Version"`
}

// PushChangesParams defines parameters for PushChanges.
type PushChangesParams struct {
	// XSchemaVersion Missing/obsolete returns 409 device_schema_outdated; invalid returns 400.
	XSchemaVersion SchemaVersion `json:"X-Schema-Version"`
}

// TillOrderHistoryParams defines parameters for TillOrderHistory.
type TillOrderHistoryParams struct {
	// Day One business date. Omitting every date filter means the current business date on the merchant's clock. Combining day with from or to is refused as ambiguous_range.
	Day *string `form:"day,omitempty" json:"day,omitempty"`

	// From First business date of a range; at most 366 days with to.
	From *string `form:"from,omitempty" json:"from,omitempty"`

	// To Last business date of a range.
	To *string `form:"to,omitempty" json:"to,omitempty"`

	// Scope Defaults to register. outlet needs viewAllOrders and is refused with forbidden_scope otherwise.
	Scope *TillOrderHistoryParamsScope `form:"scope,omitempty" json:"scope,omitempty"`

	// Status sales is every receipt that was not cancelled or refunded.
	Status *TillOrderHistoryParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// ReceiptNumber Case-insensitive prefix of the printed receipt number.
	ReceiptNumber *string `form:"receipt_number,omitempty" json:"receipt_number,omitempty"`

	// CashierId A cashier may only name themselves; anything else needs viewAllOrders and is refused with forbidden_cashier.
	CashierId *UUID `form:"cashier_id,omitempty" json:"cashier_id,omitempty"`

	// Before Opaque cursor returned by the previous page. Bound to the filter it was issued for; a cursor from an older contract is refused with invalid_cursor.
	Before *string `form:"before,omitempty" json:"before,omitempty"`

	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// TillOrderHistoryParamsScope defines parameters for TillOrderHistory.
type TillOrderHistoryParamsScope string

// TillOrderHistoryParamsStatus defines parameters for TillOrderHistory.
type TillOrderHistoryParamsStatus string

// GetTillRecoveryParams defines parameters for GetTillRecovery.
type GetTillRecoveryParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// TillReportSalesParams defines parameters for TillReportSales.
type TillReportSalesParams struct {
	// Period Resolved on the merchant's clock. Omitted with from and to present means custom; omitted entirely means today. An unknown value falls back to today rather than failing, because a dashboard is a glance.
	Period *TillReportSalesParamsPeriod `form:"period,omitempty" json:"period,omitempty"`

	// From First business date; used only with period=custom. At most 366 days with to.
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`

	// To Last business date; used only with period=custom.
	To *ReportTo `form:"to,omitempty" json:"to,omitempty"`

	// OutletId The device's own outlet when omitted. Another outlet, or the literal "all" for every outlet, needs manageOutlets; otherwise the request is refused rather than narrowed, so a total is never quietly one branch.
	OutletId *ReportOutlet `form:"outlet_id,omitempty" json:"outlet_id,omitempty"`

	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// TillReportSalesParamsPeriod defines parameters for TillReportSales.
type TillReportSalesParamsPeriod string

// TillReportSummaryParams defines parameters for TillReportSummary.
type TillReportSummaryParams struct {
	// Period Resolved on the merchant's clock. Omitted with from and to present means custom; omitted entirely means today. An unknown value falls back to today rather than failing, because a dashboard is a glance.
	Period *TillReportSummaryParamsPeriod `form:"period,omitempty" json:"period,omitempty"`

	// From First business date; used only with period=custom. At most 366 days with to.
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`

	// To Last business date; used only with period=custom.
	To *ReportTo `form:"to,omitempty" json:"to,omitempty"`

	// OutletId The device's own outlet when omitted. Another outlet, or the literal "all" for every outlet, needs manageOutlets; otherwise the request is refused rather than narrowed, so a total is never quietly one branch.
	OutletId *ReportOutlet `form:"outlet_id,omitempty" json:"outlet_id,omitempty"`

	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// TillReportSummaryParamsPeriod defines parameters for TillReportSummary.
type TillReportSummaryParamsPeriod string

// CurrentTillSessionParams defines parameters for CurrentTillSession.
type CurrentTillSessionParams struct {
	// LocalSessionId Locally active session used only to discover a matching forced recovery.
	LocalSessionId *UUID `form:"local_session_id,omitempty" json:"local_session_id,omitempty"`

	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// HandoverTillSessionParams defines parameters for HandoverTillSession.
type HandoverTillSessionParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// OpenTillSessionParams defines parameters for OpenTillSession.
type OpenTillSessionParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// ActivateDeviceJSONRequestBody defines body for ActivateDevice for application/json ContentType.
type ActivateDeviceJSONRequestBody = ActivateRequest

// PushChangesJSONRequestBody defines body for PushChanges for application/json ContentType.
type PushChangesJSONRequestBody = PushRequest

// TillLoginJSONRequestBody defines body for TillLogin for application/json ContentType.
type TillLoginJSONRequestBody = TillLoginRequest

// HandoverTillSessionJSONRequestBody defines body for HandoverTillSession for application/json ContentType.
type HandoverTillSessionJSONRequestBody = TillHandoverRequest

// OpenTillSessionJSONRequestBody defines body for OpenTillSession for application/json ContentType.
type OpenTillSessionJSONRequestBody = Session
