// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package wire

import (
	rawjson "encoding/json"
)

// Defines values for BillStatus.
const (
	BillStatusCancelled BillStatus = "cancelled"
	BillStatusOpen      BillStatus = "open"
)

// Valid indicates whether the value is a known member of the BillStatus enum.
func (e BillStatus) Valid() bool {
	switch e {
	case BillStatusCancelled:
		return true
	case BillStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for BillCancelDecisionsDisposition.
const (
	BillCancelDecisionsDispositionRestock BillCancelDecisionsDisposition = "restock"
	BillCancelDecisionsDispositionWaste   BillCancelDecisionsDisposition = "waste"
)

// Valid indicates whether the value is a known member of the BillCancelDecisionsDisposition enum.
func (e BillCancelDecisionsDisposition) Valid() bool {
	switch e {
	case BillCancelDecisionsDispositionRestock:
		return true
	case BillCancelDecisionsDispositionWaste:
		return true
	default:
		return false
	}
}

// Defines values for BillLinePriceSource.
const (
	BillLinePriceSourceBase            BillLinePriceSource = "base"
	BillLinePriceSourceCustom          BillLinePriceSource = "custom"
	BillLinePriceSourceOutletSalesType BillLinePriceSource = "outlet_sales_type"
	BillLinePriceSourceSalesType       BillLinePriceSource = "sales_type"
)

// Valid indicates whether the value is a known member of the BillLinePriceSource enum.
func (e BillLinePriceSource) Valid() bool {
	switch e {
	case BillLinePriceSourceBase:
		return true
	case BillLinePriceSourceCustom:
		return true
	case BillLinePriceSourceOutletSalesType:
		return true
	case BillLinePriceSourceSalesType:
		return true
	default:
		return false
	}
}

// Defines values for BillPricingDiscountSource.
const (
	Manual BillPricingDiscountSource = "manual"
	Named  BillPricingDiscountSource = "named"
	None   BillPricingDiscountSource = "none"
	Promo  BillPricingDiscountSource = "promo"
)

// Valid indicates whether the value is a known member of the BillPricingDiscountSource enum.
func (e BillPricingDiscountSource) Valid() bool {
	switch e {
	case Manual:
		return true
	case Named:
		return true
	case None:
		return true
	case Promo:
		return true
	default:
		return false
	}
}

// Defines values for BillPricingRoundingMode.
const (
	BillPricingRoundingModeDown    BillPricingRoundingMode = "down"
	BillPricingRoundingModeNearest BillPricingRoundingMode = "nearest"
	BillPricingRoundingModeUp      BillPricingRoundingMode = "up"
)

// Valid indicates whether the value is a known member of the BillPricingRoundingMode enum.
func (e BillPricingRoundingMode) Valid() bool {
	switch e {
	case BillPricingRoundingModeDown:
		return true
	case BillPricingRoundingModeNearest:
		return true
	case BillPricingRoundingModeUp:
		return true
	default:
		return false
	}
}

// Defines values for BillPricingTaxMode.
const (
	BillPricingTaxModeExclusive BillPricingTaxMode = "exclusive"
	BillPricingTaxModeInclusive BillPricingTaxMode = "inclusive"
)

// Valid indicates whether the value is a known member of the BillPricingTaxMode enum.
func (e BillPricingTaxMode) Valid() bool {
	switch e {
	case BillPricingTaxModeExclusive:
		return true
	case BillPricingTaxModeInclusive:
		return true
	default:
		return false
	}
}

// Defines values for DiscountRowKind.
const (
	DiscountRowKindAmount  DiscountRowKind = "amount"
	DiscountRowKindPercent DiscountRowKind = "percent"
)

// Valid indicates whether the value is a known member of the DiscountRowKind enum.
func (e DiscountRowKind) Valid() bool {
	switch e {
	case DiscountRowKindAmount:
		return true
	case DiscountRowKindPercent:
		return true
	default:
		return false
	}
}

// Defines values for DiscountRowScope.
const (
	DiscountRowScopeBill DiscountRowScope = "bill"
	DiscountRowScopeItem DiscountRowScope = "item"
)

// Valid indicates whether the value is a known member of the DiscountRowScope enum.
func (e DiscountRowScope) Valid() bool {
	switch e {
	case DiscountRowScopeBill:
		return true
	case DiscountRowScopeItem:
		return true
	default:
		return false
	}
}

// Defines values for DiscountSpecKind.
const (
	DiscountSpecKindAmount  DiscountSpecKind = "amount"
	DiscountSpecKindPercent DiscountSpecKind = "percent"
)

// Valid indicates whether the value is a known member of the DiscountSpecKind enum.
func (e DiscountSpecKind) Valid() bool {
	switch e {
	case DiscountSpecKindAmount:
		return true
	case DiscountSpecKindPercent:
		return true
	default:
		return false
	}
}

// Defines values for KitchenDispatchStatus.
const (
	KitchenDispatchStatusCancelled KitchenDispatchStatus = "cancelled"
	KitchenDispatchStatusPreparing KitchenDispatchStatus = "preparing"
	KitchenDispatchStatusQueued    KitchenDispatchStatus = "queued"
	KitchenDispatchStatusReady     KitchenDispatchStatus = "ready"
	KitchenDispatchStatusServed    KitchenDispatchStatus = "served"
)

// Valid indicates whether the value is a known member of the KitchenDispatchStatus enum.
func (e KitchenDispatchStatus) Valid() bool {
	switch e {
	case KitchenDispatchStatusCancelled:
		return true
	case KitchenDispatchStatusPreparing:
		return true
	case KitchenDispatchStatusQueued:
		return true
	case KitchenDispatchStatusReady:
		return true
	case KitchenDispatchStatusServed:
		return true
	default:
		return false
	}
}

// Defines values for ManifestEntityApply.
const (
	Replace ManifestEntityApply = "replace"
	Upsert  ManifestEntityApply = "upsert"
)

// Valid indicates whether the value is a known member of the ManifestEntityApply enum.
func (e ManifestEntityApply) Valid() bool {
	switch e {
	case Replace:
		return true
	case Upsert:
		return true
	default:
		return false
	}
}

// Defines values for ManifestEntityScope.
const (
	ManifestEntityScopeCompany ManifestEntityScope = "company"
	ManifestEntityScopeOutlet  ManifestEntityScope = "outlet"
)

// Valid indicates whether the value is a known member of the ManifestEntityScope enum.
func (e ManifestEntityScope) Valid() bool {
	switch e {
	case ManifestEntityScopeCompany:
		return true
	case ManifestEntityScopeOutlet:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	OrderStatusCancelled OrderStatus = "cancelled"
	OrderStatusPaid      OrderStatus = "paid"
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusPreparing OrderStatus = "preparing"
	OrderStatusReady     OrderStatus = "ready"
	OrderStatusRefunded  OrderStatus = "refunded"
	OrderStatusServed    OrderStatus = "served"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case OrderStatusCancelled:
		return true
	case OrderStatusPaid:
		return true
	case OrderStatusPending:
		return true
	case OrderStatusPreparing:
		return true
	case OrderStatusReady:
		return true
	case OrderStatusRefunded:
		return true
	case OrderStatusServed:
		return true
	default:
		return false
	}
}

// Defines values for OrderItemPriceSource.
const (
	OrderItemPriceSourceBase            OrderItemPriceSource = "base"
	OrderItemPriceSourceCustom          OrderItemPriceSource = "custom"
	OrderItemPriceSourceOutletSalesType OrderItemPriceSource = "outlet_sales_type"
	OrderItemPriceSourceSalesType       OrderItemPriceSource = "sales_type"
)

// Valid indicates whether the value is a known member of the OrderItemPriceSource enum.
func (e OrderItemPriceSource) Valid() bool {
	switch e {
	case OrderItemPriceSourceBase:
		return true
	case OrderItemPriceSourceCustom:
		return true
	case OrderItemPriceSourceOutletSalesType:
		return true
	case OrderItemPriceSourceSalesType:
		return true
	default:
		return false
	}
}

// Defines values for OutletSettingsRowBillModel.
const (
	OutletSettingsRowBillModelLegacy OutletSettingsRowBillModel = "legacy"
	OutletSettingsRowBillModelV1     OutletSettingsRowBillModel = "v1"
)

// Valid indicates whether the value is a known member of the OutletSettingsRowBillModel enum.
func (e OutletSettingsRowBillModel) Valid() bool {
	switch e {
	case OutletSettingsRowBillModelLegacy:
		return true
	case OutletSettingsRowBillModelV1:
		return true
	default:
		return false
	}
}

// Defines values for OutletSettingsRowPricingModel.
const (
	OutletSettingsRowPricingModelLegacy OutletSettingsRowPricingModel = "legacy"
	OutletSettingsRowPricingModelV2     OutletSettingsRowPricingModel = "v2"
)

// Valid indicates whether the value is a known member of the OutletSettingsRowPricingModel enum.
func (e OutletSettingsRowPricingModel) Valid() bool {
	switch e {
	case OutletSettingsRowPricingModelLegacy:
		return true
	case OutletSettingsRowPricingModelV2:
		return true
	default:
		return false
	}
}

// Defines values for PaymentMethodRowKind.
const (
	Card     PaymentMethodRowKind = "card"
	Cash     PaymentMethodRowKind = "cash"
	Ewallet  PaymentMethodRowKind = "ewallet"
	Other    PaymentMethodRowKind = "other"
	Qris     PaymentMethodRowKind = "qris"
	Transfer PaymentMethodRowKind = "transfer"
)

// Valid indicates whether the value is a known member of the PaymentMethodRowKind enum.
func (e PaymentMethodRowKind) Valid() bool {
	switch e {
	case Card:
		return true
	case Cash:
		return true
	case Ewallet:
		return true
	case Other:
		return true
	case Qris:
		return true
	case Transfer:
		return true
	default:
		return false
	}
}

// Defines values for PricingSnapshotRoundingMode.
const (
	PricingSnapshotRoundingModeDown    PricingSnapshotRoundingMode = "down"
	PricingSnapshotRoundingModeNearest PricingSnapshotRoundingMode = "nearest"
	PricingSnapshotRoundingModeUp      PricingSnapshotRoundingMode = "up"
)

// Valid indicates whether the value is a known member of the PricingSnapshotRoundingMode enum.
func (e PricingSnapshotRoundingMode) Valid() bool {
	switch e {
	case PricingSnapshotRoundingModeDown:
		return true
	case PricingSnapshotRoundingModeNearest:
		return true
	case PricingSnapshotRoundingModeUp:
		return true
	default:
		return false
	}
}

// Defines values for PricingSnapshotTaxMode.
const (
	PricingSnapshotTaxModeExclusive PricingSnapshotTaxMode = "exclusive"
	PricingSnapshotTaxModeInclusive PricingSnapshotTaxMode = "inclusive"
)

// Valid indicates whether the value is a known member of the PricingSnapshotTaxMode enum.
func (e PricingSnapshotTaxMode) Valid() bool {
	switch e {
	case PricingSnapshotTaxModeExclusive:
		return true
	case PricingSnapshotTaxModeInclusive:
		return true
	default:
		return false
	}
}

// Defines values for PushResultCode.
const (
	Archived          PushResultCode = "archived"
	BillNotOwned      PushResultCode = "bill_not_owned"
	DependencyPending PushResultCode = "dependency_pending"
	Duplicate         PushResultCode = "duplicate"
	RecoveryRequired  PushResultCode = "recovery_required"
	RegisterBusy      PushResultCode = "register_busy"
	SchemaRejected    PushResultCode = "schema_rejected"
	ServerUnavailable PushResultCode = "server_unavailable"
	SessionClosed     PushResultCode = "session_closed"
	Settled           PushResultCode = "settled"
	StaleRevision     PushResultCode = "stale_revision"
	UnknownEntity     PushResultCode = "unknown_entity"
)

// Valid indicates whether the value is a known member of the PushResultCode enum.
func (e PushResultCode) Valid() bool {
	switch e {
	case Archived:
		return true
	case BillNotOwned:
		return true
	case DependencyPending:
		return true
	case Duplicate:
		return true
	case RecoveryRequired:
		return true
	case RegisterBusy:
		return true
	case SchemaRejected:
		return true
	case ServerUnavailable:
		return true
	case SessionClosed:
		return true
	case Settled:
		return true
	case StaleRevision:
		return true
	case UnknownEntity:
		return true
	default:
		return false
	}
}

// Defines values for PushResultOutcome.
const (
	Applied    PushResultOutcome = "applied"
	Superseded PushResultOutcome = "superseded"
)

// Valid indicates whether the value is a known member of the PushResultOutcome enum.
func (e PushResultOutcome) Valid() bool {
	switch e {
	case Applied:
		return true
	case Superseded:
		return true
	default:
		return false
	}
}

// Defines values for PushResultStatus.
const (
	Accepted PushResultStatus = "accepted"
	Rejected PushResultStatus = "rejected"
	Retry    PushResultStatus = "retry"
)

// Valid indicates whether the value is a known member of the PushResultStatus enum.
func (e PushResultStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Rejected:
		return true
	case Retry:
		return true
	default:
		return false
	}
}

// Defines values for StockMovementReason.
const (
	StockMovementReasonCorrection StockMovementReason = "correction"
	StockMovementReasonCount      StockMovementReason = "count"
	StockMovementReasonOpening    StockMovementReason = "opening"
	StockMovementReasonReceived   StockMovementReason = "received"
	StockMovementReasonSale       StockMovementReason = "sale"
	StockMovementReasonVoidReturn StockMovementReason = "voidReturn"
	StockMovementReasonWaste      StockMovementReason = "waste"
)

// Valid indicates whether the value is a known member of the StockMovementReason enum.
func (e StockMovementReason) Valid() bool {
	switch e {
	case StockMovementReasonCorrection:
		return true
	case StockMovementReasonCount:
		return true
	case StockMovementReasonOpening:
		return true
	case StockMovementReasonReceived:
		return true
	case StockMovementReasonSale:
		return true
	case StockMovementReasonVoidReturn:
		return true
	case StockMovementReasonWaste:
		return true
	default:
		return false
	}
}

// Defines values for TableStatusEventStatus.
const (
	Available TableStatusEventStatus = "available"
	Occupied  TableStatusEventStatus = "occupied"
	Reserved  TableStatusEventStatus = "reserved"
)

// Valid indicates whether the value is a known member of the TableStatusEventStatus enum.
func (e TableStatusEventStatus) Valid() bool {
	switch e {
	case Available:
		return true
	case Occupied:
		return true
	case Reserved:
		return true
	default:
		return false
	}
}

// Defines values for TillBillSummaryStatus.
const (
	TillBillSummaryStatusCancelled TillBillSummaryStatus = "cancelled"
	TillBillSummaryStatusClosed    TillBillSummaryStatus = "closed"
	TillBillSummaryStatusOpen      TillBillSummaryStatus = "open"
)

// Valid indicates whether the value is a known member of the TillBillSummaryStatus enum.
func (e TillBillSummaryStatus) Valid() bool {
	switch e {
	case TillBillSummaryStatusCancelled:
		return true
	case TillBillSummaryStatusClosed:
		return true
	case TillBillSummaryStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for TillDispatchSummaryStatus.
const (
	TillDispatchSummaryStatusCancelled TillDispatchSummaryStatus = "cancelled"
	TillDispatchSummaryStatusPreparing TillDispatchSummaryStatus = "preparing"
	TillDispatchSummaryStatusQueued    TillDispatchSummaryStatus = "queued"
	TillDispatchSummaryStatusReady     TillDispatchSummaryStatus = "ready"
	TillDispatchSummaryStatusServed    TillDispatchSummaryStatus = "served"
)

// Valid indicates whether the value is a known member of the TillDispatchSummaryStatus enum.
func (e TillDispatchSummaryStatus) Valid() bool {
	switch e {
	case TillDispatchSummaryStatusCancelled:
		return true
	case TillDispatchSummaryStatusPreparing:
		return true
	case TillDispatchSummaryStatusQueued:
		return true
	case TillDispatchSummaryStatusReady:
		return true
	case TillDispatchSummaryStatusServed:
		return true
	default:
		return false
	}
}

// Defines values for TillHistoryPageScope.
const (
	TillHistoryPageScopeOutlet   TillHistoryPageScope = "outlet"
	TillHistoryPageScopeRegister TillHistoryPageScope = "register"
)

// Valid indicates whether the value is a known member of the TillHistoryPageScope enum.
func (e TillHistoryPageScope) Valid() bool {
	switch e {
	case TillHistoryPageScopeOutlet:
		return true
	case TillHistoryPageScopeRegister:
		return true
	default:
		return false
	}
}

// Defines values for TillRecoveryReconciliationBasis.
const (
	DeviceChecked     TillRecoveryReconciliationBasis = "device_checked"
	DeviceUnavailable TillRecoveryReconciliationBasis = "device_unavailable"
)

// Valid indicates whether the value is a known member of the TillRecoveryReconciliationBasis enum.
func (e TillRecoveryReconciliationBasis) Valid() bool {
	switch e {
	case DeviceChecked:
		return true
	case DeviceUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for TillRecoveryStatus.
const (
	RecoveryOpen       TillRecoveryStatus = "open"
	RecoveryReconciled TillRecoveryStatus = "reconciled"
)

// Valid indicates whether the value is a known member of the TillRecoveryStatus enum.
func (e TillRecoveryStatus) Valid() bool {
	switch e {
	case RecoveryOpen:
		return true
	case RecoveryReconciled:
		return true
	default:
		return false
	}
}

// Defines values for TillRecoveryItemStatus.
const (
	RecoveryItemAccepted  TillRecoveryItemStatus = "accepted"
	RecoveryItemDiscarded TillRecoveryItemStatus = "discarded"
	RecoveryItemPending   TillRecoveryItemStatus = "pending"
)

// Valid indicates whether the value is a known member of the TillRecoveryItemStatus enum.
func (e TillRecoveryItemStatus) Valid() bool {
	switch e {
	case RecoveryItemAccepted:
		return true
	case RecoveryItemDiscarded:
		return true
	case RecoveryItemPending:
		return true
	default:
		return false
	}
}

// Defines values for ReportPeriod.
const (
	ReportPeriodCustom    ReportPeriod = "custom"
	ReportPeriodLast7     ReportPeriod = "last7"
	ReportPeriodMonth     ReportPeriod = "month"
	ReportPeriodToday     ReportPeriod = "today"
	ReportPeriodYesterday ReportPeriod = "yesterday"
)

// Valid indicates whether the value is a known member of the ReportPeriod enum.
func (e ReportPeriod) Valid() bool {
	switch e {
	case ReportPeriodCustom:
		return true
	case ReportPeriodLast7:
		return true
	case ReportPeriodMonth:
		return true
	case ReportPeriodToday:
		return true
	case ReportPeriodYesterday:
		return true
	default:
		return false
	}
}

// Defines values for TillOrderHistoryParamsScope.
const (
	TillOrderHistoryParamsScopeOutlet   TillOrderHistoryParamsScope = "outlet"
	TillOrderHistoryParamsScopeRegister TillOrderHistoryParamsScope = "register"
)

// Valid indicates whether the value is a known member of the TillOrderHistoryParamsScope enum.
func (e TillOrderHistoryParamsScope) Valid() bool {
	switch e {
	case TillOrderHistoryParamsScopeOutlet:
		return true
	case TillOrderHistoryParamsScopeRegister:
		return true
	default:
		return false
	}
}

// Defines values for TillOrderHistoryParamsStatus.
const (
	TillOrderHistoryParamsStatusCancelled TillOrderHistoryParamsStatus = "cancelled"
	TillOrderHistoryParamsStatusPaid      TillOrderHistoryParamsStatus = "paid"
	TillOrderHistoryParamsStatusPending   TillOrderHistoryParamsStatus = "pending"
	TillOrderHistoryParamsStatusPreparing TillOrderHistoryParamsStatus = "preparing"
	TillOrderHistoryParamsStatusReady     TillOrderHistoryParamsStatus = "ready"
	TillOrderHistoryParamsStatusRefunded  TillOrderHistoryParamsStatus = "refunded"
	TillOrderHistoryParamsStatusSales     TillOrderHistoryParamsStatus = "sales"
	TillOrderHistoryParamsStatusServed    TillOrderHistoryParamsStatus = "served"
)

// Valid indicates whether the value is a known member of the TillOrderHistoryParamsStatus enum.
func (e TillOrderHistoryParamsStatus) Valid() bool {
	switch e {
	case TillOrderHistoryParamsStatusCancelled:
		return true
	case TillOrderHistoryParamsStatusPaid:
		return true
	case TillOrderHistoryParamsStatusPending:
		return true
	case TillOrderHistoryParamsStatusPreparing:
		return true
	case TillOrderHistoryParamsStatusReady:
		return true
	case TillOrderHistoryParamsStatusRefunded:
		return true
	case TillOrderHistoryParamsStatusSales:
		return true
	case TillOrderHistoryParamsStatusServed:
		return true
	default:
		return false
	}
}

// Defines values for TillReportSalesParamsPeriod.
const (
	TillReportSalesParamsPeriodCustom    TillReportSalesParamsPeriod = "custom"
	TillReportSalesParamsPeriodLast7     TillReportSalesParamsPeriod = "last7"
	TillReportSalesParamsPeriodMonth     TillReportSalesParamsPeriod = "month"
	TillReportSalesParamsPeriodToday     TillReportSalesParamsPeriod = "today"
	TillReportSalesParamsPeriodYesterday TillReportSalesParamsPeriod = "yesterday"
)

// Valid indicates whether the value is a known member of the TillReportSalesParamsPeriod enum.
func (e TillReportSalesParamsPeriod) Valid() bool {
	switch e {
	case TillReportSalesParamsPeriodCustom:
		return true
	case TillReportSalesParamsPeriodLast7:
		return true
	case TillReportSalesParamsPeriodMonth:
		return true
	case TillReportSalesParamsPeriodToday:
		return true
	case TillReportSalesParamsPeriodYesterday:
		return true
	default:
		return false
	}
}

// Defines values for TillReportSummaryParamsPeriod.
const (
	TillReportSummaryParamsPeriodCustom    TillReportSummaryParamsPeriod = "custom"
	TillReportSummaryParamsPeriodLast7     TillReportSummaryParamsPeriod = "last7"
	TillReportSummaryParamsPeriodMonth     TillReportSummaryParamsPeriod = "month"
	TillReportSummaryParamsPeriodToday     TillReportSummaryParamsPeriod = "today"
	TillReportSummaryParamsPeriodYesterday TillReportSummaryParamsPeriod = "yesterday"
)

// Valid indicates whether the value is a known member of the TillReportSummaryParamsPeriod enum.
func (e TillReportSummaryParamsPeriod) Valid() bool {
	switch e {
	case TillReportSummaryParamsPeriodCustom:
		return true
	case TillReportSummaryParamsPeriodLast7:
		return true
	case TillReportSummaryParamsPeriodMonth:
		return true
	case TillReportSummaryParamsPeriodToday:
		return true
	case TillReportSummaryParamsPeriodYesterday:
		return true
	default:
		return false
	}
}

// ActivateRequest defines model for ActivateRequest.
type ActivateRequest struct {
	Code       string  `json:"code"`
	DeviceUuid ID      `json:"device_uuid"`
	Label      *string `json:"label,omitempty"`
	Platform   *string `json:"platform,omitempty"`
}

// ActivateResponse defines model for ActivateResponse.
type ActivateResponse struct {
	Data struct {
		Device           Device   `json:"device"`
		Outlet           Outlet   `json:"outlet"`
		PosRegister      Register `json:"pos_register"`
		Tenant           Tenant   `json:"tenant"`
		Token            string   `json:"token"`
		TokenExpiresAtMs Millis   `json:"token_expires_at_ms"`
	} `json:"data"`
}

// Bill Fase 4. One bill as its owning till last saved it, at a revision. The
// till numbers revisions itself and every save is a newer one; the server
// keeps the last accepted snapshot and accepts an exact retry of it. The
// snapshot is refused as bill_not_owned when this till is not the owner or
// owner_generation is not the bill's current one; a line already
// dispatched must appear unchanged in every later revision. status
// cancelled is terminal and needs cancel; closed is never pushed — the
// settling receipt closes the bill. Saving takes no money and moves no
// stock.
type Bill struct {
	// Cancel Why an unpaid bill was cancelled, who allowed it and, for every line
	// already sent to the kitchen, whether it came back to the shelf
	// (restock) or was made and thrown away (waste). Waste is a
	// classification of a consumption that already happened, never a second
	// debit. stock_movements holds only the voidReturn movements of the
	// restocked lines, bounded by what the bill's dispatches consumed.
	Cancel          *BillCancel `json:"cancel,omitempty"`
	CreatedById     *string     `json:"created_by_id,omitempty"`
	CreatedByName   Name        `json:"created_by_name"`
	CustomerId      *string     `json:"customer_id,omitempty"`
	CustomerName    *string     `json:"customer_name,omitempty"`
	Id              UUID        `json:"id"`
	Lines           []BillLine  `json:"lines"`
	Note            *string     `json:"note,omitempty"`
	Number          string      `json:"number"`
	OpenedAtMs      Millis      `json:"opened_at_ms"`
	OwnerGeneration int64       `json:"owner_generation"`
	PosSessionId    UUID        `json:"pos_session_id"`

	// Pricing The configuration frozen when the bill was first saved, so a sync that changes a rate never re-prices a bill a guest was already quoted.
	Pricing        BillPricing `json:"pricing"`
	Revision       int64       `json:"revision"`
	SalesTypeId    *string     `json:"sales_type_id,omitempty"`
	SalesTypeName  *string     `json:"sales_type_name,omitempty"`
	ServedById     *string     `json:"served_by_id,omitempty"`
	ServedByName   *string     `json:"served_by_name,omitempty"`
	Status         BillStatus  `json:"status"`
	TableId        *string     `json:"table_id,omitempty"`
	TableName      *string     `json:"table_name,omitempty"`
	TableSessionId *UUID       `json:"table_session_id,omitempty"`
	Type           string      `json:"type"`
}

// BillStatus defines model for Bill.Status.
type BillStatus string

// BillCancel Why an unpaid bill was cancelled, who allowed it and, for every line
// already sent to the kitchen, whether it came back to the shelf
// (restock) or was made and thrown away (waste). Waste is a
// classification of a consumption that already happened, never a second
// debit. stock_movements holds only the voidReturn movements of the
// restocked lines, bounded by what the bill's dispatches consumed.
type BillCancel struct {
	AuthorizedBy   Name    `json:"authorized_by"`
	AuthorizedById *string `json:"authorized_by_id,omitempty"`
	CancelledAtMs  Millis  `json:"cancelled_at_ms"`
	Decisions      []struct {
		BillLineId  UUID                           `json:"bill_line_id"`
		Disposition BillCancelDecisionsDisposition `json:"disposition"`
	} `json:"decisions"`
	Reason         string          `json:"reason"`
	StockMovements []StockMovement `json:"stock_movements"`
}

// BillCancelDecisionsDisposition defines model for BillCancel.Decisions.Disposition.
type BillCancelDecisionsDisposition string

// BillLine One line of a bill, priced when it was added. unit_price already includes variant and modifier deltas.
type BillLine struct {
	BasePrice                    *Money               `json:"base_price,omitempty"`
	BrandId                      *string              `json:"brand_id,omitempty"`
	CategoryId                   *string              `json:"category_id,omitempty"`
	CategoryName                 *string              `json:"category_name,omitempty"`
	Custom                       bool                 `json:"custom"`
	Discount                     *DiscountSpec        `json:"discount,omitempty"`
	Id                           UUID                 `json:"id"`
	LineDiscountAuthorizedById   *string              `json:"line_discount_authorized_by_id,omitempty"`
	LineDiscountAuthorizedByName *string              `json:"line_discount_authorized_by_name,omitempty"`
	LineDiscountId               *string              `json:"line_discount_id,omitempty"`
	LineDiscountName             *string              `json:"line_discount_name,omitempty"`
	Modifiers                    []BillLineModifier   `json:"modifiers"`
	Note                         *string              `json:"note,omitempty"`
	PriceSource                  *BillLinePriceSource `json:"price_source,omitempty"`
	ProductId                    *string              `json:"product_id,omitempty"`
	ProductName                  Name                 `json:"product_name"`
	Quantity                     int                  `json:"quantity"`
	Seq                          int                  `json:"seq"`
	TaxRateBp                    *int                 `json:"tax_rate_bp,omitempty"`
	UnitCost                     *int64               `json:"unit_cost,omitempty"`
	UnitPrice                    Money                `json:"unit_price"`
	VariantId                    *string              `json:"variant_id,omitempty"`
	VariantName                  *string              `json:"variant_name,omitempty"`
}

// BillLinePriceSource defines model for BillLine.PriceSource.
type BillLinePriceSource string

// BillLineModifier defines model for BillLineModifier.
type BillLineModifier struct {
	GroupId    *string `json:"group_id,omitempty"`
	GroupName  Name    `json:"group_name"`
	OptionId   *string `json:"option_id,omitempty"`
	OptionName Name    `json:"option_name"`
	PriceDelta int64   `json:"price_delta"`
}

// BillPricing The configuration frozen when the bill was first saved, so a sync that changes a rate never re-prices a bill a guest was already quoted.
type BillPricing struct {
	BillDiscount             *DiscountSpec             `json:"bill_discount,omitempty"`
	DefaultTaxRateBp         int                       `json:"default_tax_rate_bp"`
	DiscountAuthorizedById   *string                   `json:"discount_authorized_by_id,omitempty"`
	DiscountAuthorizedByName *string                   `json:"discount_authorized_by_name,omitempty"`
	DiscountId               *string                   `json:"discount_id,omitempty"`
	DiscountName             *string                   `json:"discount_name,omitempty"`
	DiscountSource           BillPricingDiscountSource `json:"discount_source"`
	PromoId                  *string                   `json:"promo_id,omitempty"`
	PromoName                *string                   `json:"promo_name,omitempty"`
	RoundingMode             BillPricingRoundingMode   `json:"rounding_mode"`
	RoundingUnit             int                       `json:"rounding_unit"`
	ServiceRateBp            int                       `json:"service_rate_bp"`
	ServiceTaxable           bool                      `json:"service_taxable"`
	TaxMode                  BillPricingTaxMode        `json:"tax_mode"`
	Version                  int                       `json:"version"`
}

// BillPricingDiscountSource defines model for BillPricing.DiscountSource.
type BillPricingDiscountSource string

// BillPricingRoundingMode defines model for BillPricing.RoundingMode.
type BillPricingRoundingMode string

// BillPricingTaxMode defines model for BillPricing.TaxMode.
type BillPricingTaxMode string

// Binding defines model for Binding.
type Binding struct {
	Device      Device   `json:"device"`
	Outlet      Outlet   `json:"outlet"`
	PosRegister Register `json:"pos_register"`
	Tenant      Tenant   `json:"tenant"`
}

// BrandRow defines model for BrandRow.
type BrandRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	SortOrder   int64  `json:"sort_order"`
	SyncSeq     int64  `json:"sync_seq"`
}

// BusinessSettingsRow The merchant's defaults. Its presence is what says the business has been configured in the Backoffice.
type BusinessSettingsRow struct {
	DeletedAtMs    *int64  `json:"deleted_at_ms"`
	Id             string  `json:"id"`
	ReceiptFooter  *string `json:"receipt_footer"`
	ReceiptLogoUrl *string `json:"receipt_logo_url"`
	RoundingMode   string  `json:"rounding_mode"`
	RoundingUnit   int64   `json:"rounding_unit"`
	ServiceEnabled bool    `json:"service_enabled"`
	ServiceRateBp  int64   `json:"service_rate_bp"`
	ServiceTaxable bool    `json:"service_taxable"`
	SyncSeq        int64   `json:"sync_seq"`
	TaxMode        string  `json:"tax_mode"`
	TaxRateBp      int64   `json:"tax_rate_bp"`
}

// CategoryRow defines model for CategoryRow.
type CategoryRow struct {
	DeletedAtMs *int64  `json:"deleted_at_ms"`
	IconKey     *string `json:"icon_key"`
	Id          string  `json:"id"`
	IsPopular   bool    `json:"is_popular"`
	Name        string  `json:"name"`
	SortOrder   int64   `json:"sort_order"`
	SyncSeq     int64   `json:"sync_seq"`
}

// Changes defines model for Changes.
type Changes struct {
	Cursors        map[string]int64 `json:"cursors"`
	DeviceRevision Millis           `json:"device_revision"`
	NextPollMs     int64            `json:"next_poll_ms"`
	ServerTimeMs   Millis           `json:"server_time_ms"`
}

// Customer A customer a till pushes up, created either at the counter or in the
// Backoffice. Insert-only on arrival — id is chosen by whichever side
// creates the row and is also its idempotency key; an id that already
// exists is accepted and left alone (ON CONFLICT DO NOTHING), never
// overwritten. There is no revision here because there is nothing to
// revise: editing an existing customer is a Backoffice-only action this
// entity does not carry, so a till never has to reconcile a second
// writer's edit against its own.
type Customer struct {
	Address *string `json:"address,omitempty"`
	Email   *string `json:"email,omitempty"`
	Id      UUID    `json:"id"`
	Name    string  `json:"name"`
	Note    *string `json:"note,omitempty"`
	Phone   *string `json:"phone,omitempty"`
}

// CustomerRow defines model for CustomerRow.
type CustomerRow struct {
	Active      bool    `json:"active"`
	Address     *string `json:"address"`
	DeletedAtMs *int64  `json:"deleted_at_ms"`
	Email       *string `json:"email"`
	Id          string  `json:"id"`
	Name        string  `json:"name"`
	Note        *string `json:"note"`
	Phone       *string `json:"phone"`
	SyncSeq     int64   `json:"sync_seq"`
}

// Device defines model for Device.
type Device struct {
	DeviceUuid ID      `json:"device_uuid"`
	Id         ID      `json:"id"`
	Label      *string `json:"label"`
	Platform   *string `json:"platform"`
}

// DiscountRow defines model for DiscountRow.
type DiscountRow struct {
	Active                bool             `json:"active"`
	DeletedAtMs           *int64           `json:"deleted_at_ms"`
	Id                    string           `json:"id"`
	Kind                  DiscountRowKind  `json:"kind"`
	Name                  string           `json:"name"`
	RequiresAuthorization bool             `json:"requires_authorization"`
	Scope                 DiscountRowScope `json:"scope"`
	SortOrder             int64            `json:"sort_order"`
	SyncSeq               int64            `json:"sync_seq"`

	// Value Basis points or rupiah; null means the cashier types the value.
	Value *int64 `json:"value"`
}

// DiscountRowKind defines model for DiscountRow.Kind.
type DiscountRowKind string

// DiscountRowScope defines model for DiscountRow.Scope.
type DiscountRowScope string

// DiscountSpec defines model for DiscountSpec.
type DiscountSpec struct {
	Kind DiscountSpecKind `json:"kind"`

	// Value Basis points for percent, rupiah for amount.
	Value int64 `json:"value"`
}

// DiscountSpecKind defines model for DiscountSpec.Kind.
type DiscountSpecKind string

// EmployeeRow defines model for EmployeeRow.
type EmployeeRow struct {
	Active      bool    `json:"active"`
	DeletedAtMs *int64  `json:"deleted_at_ms"`
	Id          string  `json:"id"`
	Name        string  `json:"name"`
	PinHash     *string `json:"pin_hash"`
	Role        string  `json:"role"`
	RoleId      *string `json:"role_id"`
	SortOrder   int64   `json:"sort_order"`
	SyncSeq     int64   `json:"sync_seq"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Cache    string `json:"cache"`
	Database string `json:"database"`
	Service  string `json:"service"`
	Status   string `json:"status"`
}

// ID defines model for ID.
type ID = string

// KitchenDispatch Fase 4. Lines of one bill confirmed for the kitchen, as one immutable
// batch, and the sale movements that consumed their stock — committed in
// one transaction, exactly once. lines repeats each bill line exactly as
// the bill holds it; a line the server does not hold yet, or holds
// differently, answers dependency_pending until the bill snapshot
// arrives. A later revision may change status only, forward (queued,
// preparing, ready, served); cancelled comes from cancelling the bill.
type KitchenDispatch struct {
	BillId            UUID                  `json:"bill_id"`
	EmployeeId        *string               `json:"employee_id,omitempty"`
	EmployeeName      string                `json:"employee_name"`
	Id                UUID                  `json:"id"`
	Lines             []BillLine            `json:"lines"`
	OccurredAtMs      Millis                `json:"occurred_at_ms"`
	OwnerGeneration   int64                 `json:"owner_generation"`
	PosSessionId      UUID                  `json:"pos_session_id"`
	Revision          int64                 `json:"revision"`
	Status            KitchenDispatchStatus `json:"status"`
	StatusChangedAtMs Millis                `json:"status_changed_at_ms"`
	StockMovements    []StockMovement       `json:"stock_movements"`
}

// KitchenDispatchStatus defines model for KitchenDispatch.Status.
type KitchenDispatchStatus string

// Manifest defines model for Manifest.
type Manifest struct {
	Entities      []ManifestEntity `json:"entities"`
	SchemaVersion int              `json:"schema_version"`
}

// ManifestEntity defines model for ManifestEntity.
type ManifestEntity struct {
	Apply     ManifestEntityApply `json:"apply"`
	DependsOn []string            `json:"depends_on"`
	Key       []string            `json:"key"`
	Name      string              `json:"name"`
	Pull      bool                `json:"pull"`
	Push      bool                `json:"push"`
	Scope     ManifestEntityScope `json:"scope"`
}

// ManifestEntityApply defines model for ManifestEntity.Apply.
type ManifestEntityApply string

// ManifestEntityScope defines model for ManifestEntity.Scope.
type ManifestEntityScope string

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Data Binding `json:"data"`
}

// Millis defines model for Millis.
type Millis = int64

// ModifierGroupRow defines model for ModifierGroupRow.
type ModifierGroupRow struct {
	Active        bool   `json:"active"`
	DeletedAtMs   *int64 `json:"deleted_at_ms"`
	Id            string `json:"id"`
	MaxSelect     *int64 `json:"max_select"`
	Name          string `json:"name"`
	Required      bool   `json:"required"`
	SelectionType string `json:"selection_type"`
	SortOrder     int64  `json:"sort_order"`
	SyncSeq       int64  `json:"sync_seq"`
}

// ModifierOptionRow defines model for ModifierOptionRow.
type ModifierOptionRow struct {
	Active      bool   `json:"active"`
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	GroupId     string `json:"group_id"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	PriceDelta  int64  `json:"price_delta"`
	SortOrder   int64  `json:"sort_order"`
	SyncSeq     int64  `json:"sync_seq"`
}

// Money defines model for Money.
type Money = int64

// Name defines model for Name.
type Name = string

// Order defines model for Order.
type Order struct {
	AmountPaid   Money   `json:"amount_paid"`
	AuthorizedBy *string `json:"authorized_by,omitempty"`

	// BillId Fase 4. The bill this receipt settles. Every line of the bill must already be dispatched on the server, and the receipt carries no sale movement of its own: the dispatches consumed the stock.
	BillId                   *UUID       `json:"bill_id,omitempty"`
	BusinessDate             string      `json:"business_date"`
	CashierId                *string     `json:"cashier_id,omitempty"`
	CashierName              Name        `json:"cashier_name"`
	CustomerId               *string     `json:"customer_id,omitempty"`
	CustomerName             *string     `json:"customer_name,omitempty"`
	Discount                 Money       `json:"discount"`
	DiscountAuthorizedById   *string     `json:"discount_authorized_by_id,omitempty"`
	DiscountAuthorizedByName *string     `json:"discount_authorized_by_name,omitempty"`
	DiscountId               *string     `json:"discount_id,omitempty"`
	DiscountName             *string     `json:"discount_name,omitempty"`
	Id                       UUID        `json:"id"`
	Items                    []OrderItem `json:"items"`
	Note                     *string     `json:"note,omitempty"`
	Number                   string      `json:"number"`
	OutletName               *string     `json:"outlet_name,omitempty"`
	PaymentMethod            string      `json:"payment_method"`
	PaymentMethodId          *string     `json:"payment_method_id,omitempty"`
	PaymentMethodName        *string     `json:"payment_method_name,omitempty"`
	PaymentReference         *string     `json:"payment_reference,omitempty"`
	Pb1Rate                  *float64    `json:"pb1_rate,omitempty"`
	PlacedAtMs               Millis      `json:"placed_at_ms"`
	PosName                  *string     `json:"pos_name,omitempty"`
	PosSessionId             UUID        `json:"pos_session_id"`

	// Pricing The configuration the till priced the bill with, frozen at checkout so the server can recompute it.
	Pricing *PricingSnapshot `json:"pricing,omitempty"`

	// PricingVersion Absent or 1: the legacy cart math. 2: the Fase 3 engine; its lines must reconcile with the header.
	PricingVersion *int    `json:"pricing_version,omitempty"`
	PromoName      *string `json:"promo_name,omitempty"`
	RefundedAmount *int64  `json:"refunded_amount,omitempty"`
	Revision       int64   `json:"revision"`

	// RoundingAmount Final rounding of what the customer pays; may be negative.
	RoundingAmount      *int64      `json:"rounding_amount,omitempty"`
	SalesTypeId         *string     `json:"sales_type_id,omitempty"`
	SalesTypeName       *string     `json:"sales_type_name,omitempty"`
	ServedById          *string     `json:"served_by_id,omitempty"`
	ServedByName        *string     `json:"served_by_name,omitempty"`
	ServerTimeDeltaMs   *int64      `json:"server_time_delta_ms,omitempty"`
	ServiceChargeAmount Money       `json:"service_charge_amount"`
	ServiceChargeRate   *float64    `json:"service_charge_rate,omitempty"`
	Status              OrderStatus `json:"status"`

	// StockMovements Complete immutable sale and optional return movements committed atomically with this receipt.
	StockMovements *[]StockMovement `json:"stock_movements,omitempty"`
	Subtotal       Money            `json:"subtotal"`
	TableId        *string          `json:"table_id,omitempty"`
	TableName      *string          `json:"table_name,omitempty"`
	Tax            Money            `json:"tax"`

	// TaxIncluded The part of tax already inside the prices (inclusive mode). Never more than tax.
	TaxIncluded *Money `json:"tax_included,omitempty"`
	Total       Money  `json:"total"`
	Type        string `json:"type"`

	// TzOffsetMinutes The merchant clock the business date was read from.
	TzOffsetMinutes *int    `json:"tz_offset_minutes,omitempty"`
	VoidReason      *string `json:"void_reason,omitempty"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// OrderItem unit_price is the final per-unit snapshot including variant/modifier deltas; never add modifier price_delta to it again. subtotal equals sum(unit_price * quantity).
type OrderItem struct {
	// BasePrice The resolved price before variant and modifier deltas.
	BasePrice         *Money `json:"base_price,omitempty"`
	BillDiscountShare *Money `json:"bill_discount_share,omitempty"`

	// BillLineId Fase 4. The bill line this receipt line settles, when the receipt names a bill_id.
	BillLineId   *UUID   `json:"bill_line_id,omitempty"`
	BrandId      *string `json:"brand_id,omitempty"`
	CategoryId   *string `json:"category_id,omitempty"`
	CategoryName *string `json:"category_name,omitempty"`

	// Custom A custom amount typed at the till; no product, no stock effect.
	Custom                       *bool                 `json:"custom,omitempty"`
	Discount                     *DiscountSpec         `json:"discount,omitempty"`
	Id                           UUID                  `json:"id"`
	LineDiscount                 *Money                `json:"line_discount,omitempty"`
	LineDiscountAuthorizedById   *string               `json:"line_discount_authorized_by_id,omitempty"`
	LineDiscountAuthorizedByName *string               `json:"line_discount_authorized_by_name,omitempty"`
	LineDiscountId               *string               `json:"line_discount_id,omitempty"`
	LineDiscountName             *string               `json:"line_discount_name,omitempty"`
	Modifiers                    []OrderItemModifier   `json:"modifiers"`
	NetAmount                    *Money                `json:"net_amount,omitempty"`
	Note                         *string               `json:"note,omitempty"`
	PriceSource                  *OrderItemPriceSource `json:"price_source,omitempty"`
	ProductId                    *string               `json:"product_id,omitempty"`
	ProductName                  Name                  `json:"product_name"`
	Quantity                     int                   `json:"quantity"`
	ServiceShare                 *Money                `json:"service_share,omitempty"`
	TaxAmount                    *Money                `json:"tax_amount,omitempty"`
	TaxIncluded                  *Money                `json:"tax_included,omitempty"`
	TaxRateBp                    *int                  `json:"tax_rate_bp,omitempty"`
	UnitCost                     *int64                `json:"unit_cost,omitempty"`
	UnitPrice                    Money                 `json:"unit_price"`
	VariantName                  *string               `json:"variant_name,omitempty"`
}

// OrderItemPriceSource defines model for OrderItem.PriceSource.
type OrderItemPriceSource string

// OrderItemModifier defines model for OrderItemModifier.
type OrderItemModifier struct {
	GroupName  Name  `json:"group_name"`
	Id         UUID  `json:"id"`
	OptionName Name  `json:"option_name"`
	PriceDelta int64 `json:"price_delta"`
	SortOrder  int   `json:"sort_order"`
}

// Outlet defines model for Outlet.
type Outlet struct {
	Address *string `json:"address"`
	Id      ID      `json:"id"`
	Name    string  `json:"name"`
	Phone   *string `json:"phone"`
}

// OutletProductSalesTypePriceRow defines model for OutletProductSalesTypePriceRow.
type OutletProductSalesTypePriceRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	OutletId    string `json:"outlet_id"`
	Price       int64  `json:"price"`
	ProductId   string `json:"product_id"`
	SalesTypeId string `json:"sales_type_id"`
	SyncSeq     int64  `json:"sync_seq"`
}

// OutletRow defines model for OutletRow.
type OutletRow struct {
	Active      bool    `json:"active"`
	Address     *string `json:"address"`
	DeletedAtMs *int64  `json:"deleted_at_ms"`
	Id          string  `json:"id"`
	Name        string  `json:"name"`
	SortOrder   int64   `json:"sort_order"`
	SyncSeq     int64   `json:"sync_seq"`
}

// OutletSettingsRow One outlet's overrides. Null inherits the business value; zero is a real override.
type OutletSettingsRow struct {
	// BillModel Fase 4. v1 turns on saved bills, kitchen dispatch and table seatings at this branch.
	BillModel          OutletSettingsRowBillModel    `json:"bill_model"`
	DefaultSalesTypeId *string                       `json:"default_sales_type_id"`
	DeletedAtMs        *int64                        `json:"deleted_at_ms"`
	OutletId           string                        `json:"outlet_id"`
	PaymentGroupId     *string                       `json:"payment_group_id"`
	PricingModel       OutletSettingsRowPricingModel `json:"pricing_model"`
	ReceiptFooter      *string                       `json:"receipt_footer"`
	ReceiptHeader      *string                       `json:"receipt_header"`
	RoundingMode       *string                       `json:"rounding_mode"`
	RoundingUnit       *int64                        `json:"rounding_unit"`
	SalesTypeIds       *string                       `json:"sales_type_ids"`
	ServiceEnabled     *bool                         `json:"service_enabled"`
	ServiceRateBp      *int64                        `json:"service_rate_bp"`
	ServiceTaxable     *bool                         `json:"service_taxable"`
	ShowAddress        bool                          `json:"show_address"`
	ShowPhone          bool                          `json:"show_phone"`
	SyncSeq            int64                         `json:"sync_seq"`
	TaxMode            *string                       `json:"tax_mode"`
	TaxRateBp          *int64                        `json:"tax_rate_bp"`
	TrackServer        bool                          `json:"track_server"`
}

// OutletSettingsRowBillModel Fase 4. v1 turns on saved bills, kitchen dispatch and table seatings at this branch.
type OutletSettingsRowBillModel string

// OutletSettingsRowPricingModel defines model for OutletSettingsRow.PricingModel.
type OutletSettingsRowPricingModel string

// OutletStockRow defines model for OutletStockRow.
type OutletStockRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	OutletId    string `json:"outlet_id"`
	ProductId   string `json:"product_id"`
	QtyOnHand   int64  `json:"qty_on_hand"`
	SyncSeq     int64  `json:"sync_seq"`
}

// PaymentGroupRow defines model for PaymentGroupRow.
type PaymentGroupRow struct {
	Active      bool   `json:"active"`
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	Id          string `json:"id"`
	MethodIds   string `json:"method_ids"`
	Name        string `json:"name"`
	SortOrder   int64  `json:"sort_order"`
	SyncSeq     int64  `json:"sync_seq"`
}

// PaymentMethodRow defines model for PaymentMethodRow.
type PaymentMethodRow struct {
	Active            bool                 `json:"active"`
	DeletedAtMs       *int64               `json:"deleted_at_ms"`
	Id                string               `json:"id"`
	Kind              PaymentMethodRowKind `json:"kind"`
	Name              string               `json:"name"`
	RequiresReference bool                 `json:"requires_reference"`
	SortOrder         int64                `json:"sort_order"`
	SyncSeq           int64                `json:"sync_seq"`
	SystemKey         *string              `json:"system_key"`
}

// PaymentMethodRowKind defines model for PaymentMethodRow.Kind.
type PaymentMethodRowKind string

// PricingSnapshot The configuration the till priced the bill with, frozen at checkout so the server can recompute it.
type PricingSnapshot struct {
	BillDiscount   *DiscountSpec               `json:"bill_discount,omitempty"`
	RoundingMode   PricingSnapshotRoundingMode `json:"rounding_mode"`
	RoundingUnit   int                         `json:"rounding_unit"`
	ServiceRateBp  int                         `json:"service_rate_bp"`
	ServiceTaxable bool                        `json:"service_taxable"`
	TaxMode        PricingSnapshotTaxMode      `json:"tax_mode"`
}

// PricingSnapshotRoundingMode defines model for PricingSnapshot.RoundingMode.
type PricingSnapshotRoundingMode string

// PricingSnapshotTaxMode defines model for PricingSnapshot.TaxMode.
type PricingSnapshotTaxMode string

// ProductModifierGroupRow defines model for ProductModifierGroupRow.
type ProductModifierGroupRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	GroupId     string `json:"group_id"`
	ProductId   string `json:"product_id"`
	SyncSeq     int64  `json:"sync_seq"`
}

// ProductModifierOptionRow defines model for ProductModifierOptionRow.
type ProductModifierOptionRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	IsDefault   bool   `json:"is_default"`
	OptionId    string `json:"option_id"`
	ProductId   string `json:"product_id"`
	SyncSeq     int64  `json:"sync_seq"`
}

// ProductRow defines model for ProductRow.
type ProductRow struct {
	Available   bool     `json:"available"`
	BrandId     *string  `json:"brand_id"`
	CategoryId  *string  `json:"category_id"`
	Cost        *int64   `json:"cost"`
	DeletedAtMs *int64   `json:"deleted_at_ms"`
	Description *string  `json:"description"`
	IconKey     *string  `json:"icon_key"`
	Id          string   `json:"id"`
	ImageUrl    *string  `json:"image_url"`
	IsPopular   bool     `json:"is_popular"`
	Name        string   `json:"name"`
	Price       int64    `json:"price"`
	Sku         *string  `json:"sku"`
	SortOrder   int64    `json:"sort_order"`
	SyncSeq     int64    `json:"sync_seq"`
	TaxRate     *float32 `json:"tax_rate"`
}

// ProductSalesTypePriceRow defines model for ProductSalesTypePriceRow.
type ProductSalesTypePriceRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	Price       int64  `json:"price"`
	ProductId   string `json:"product_id"`
	SalesTypeId string `json:"sales_type_id"`
	SyncSeq     int64  `json:"sync_seq"`
}

// PromoOutletRow defines model for PromoOutletRow.
type PromoOutletRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	OutletId    string `json:"outlet_id"`
	PromoId     string `json:"promo_id"`
	SyncSeq     int64  `json:"sync_seq"`
}

// PromoRow defines model for PromoRow.
type PromoRow struct {
	Active      bool   `json:"active"`
	AllOutlets  bool   `json:"all_outlets"`
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	Id          string `json:"id"`
	Kind        string `json:"kind"`
	MinSpend    int64  `json:"min_spend"`
	Name        string `json:"name"`
	SortOrder   int64  `json:"sort_order"`
	SyncSeq     int64  `json:"sync_seq"`
	Value       int64  `json:"value"`
}

// PullPage defines model for PullPage.
type PullPage struct {
	Entity        string               `json:"entity"`
	HasMore       bool                 `json:"has_more"`
	NextSeq       int64                `json:"next_seq"`
	Rows          []rawjson.RawMessage `json:"rows"`
	SchemaVersion int                  `json:"schema_version"`
}

// PushBatch defines model for PushBatch.
type PushBatch struct {
	Entity string               `json:"entity"`
	Rows   []rawjson.RawMessage `json:"rows"`
}

// PushEffect defines model for PushEffect.
type PushEffect struct {
	BalanceAfter int64 `json:"balance_after"`
	Id           UUID  `json:"id"`
	StockSeq     int64 `json:"stock_seq"`
}

// PushRequest defines model for PushRequest.
type PushRequest struct {
	Batches []PushBatch `json:"batches"`
}

// PushResponse defines model for PushResponse.
type PushResponse struct {
	Results      []PushResult `json:"results"`
	ServerTimeMs Millis       `json:"server_time_ms"`
}

// PushResult defines model for PushResult.
type PushResult struct {
	// BalanceAfter For an accepted stock movement, the outlet's quantity immediately after it (a count's computed delta included).
	BalanceAfter *int64          `json:"balance_after,omitempty"`
	BatchIndex   int             `json:"batch_index"`
	BusinessDate *string         `json:"business_date,omitempty"`
	Code         *PushResultCode `json:"code,omitempty"`

	// Effects For an accepted kitchen dispatch, bill or receipt, what each stock movement it committed did — the same stock_seq and balance_after a standalone movement returns, so the till stops counting it once a snapshot includes it.
	Effects            *[]PushEffect `json:"effects,omitempty"`
	Entity             string        `json:"entity"`
	HolderEmployeeName *string       `json:"holder_employee_name,omitempty"`
	HolderSessionId    *string       `json:"holder_session_id,omitempty"`
	Id                 *string       `json:"id,omitempty"`
	Inserted           *bool         `json:"inserted,omitempty"`
	Message            *string       `json:"message,omitempty"`

	// Outcome For an accepted table status event, whether the table took its status (applied) or kept a later change by another till (superseded).
	Outcome    *PushResultOutcome `json:"outcome,omitempty"`
	RecoveryId *UUID              `json:"recovery_id,omitempty"`
	Revision   *int64             `json:"revision,omitempty"`
	RowIndex   int                `json:"row_index"`
	Status     PushResultStatus   `json:"status"`

	// StatusSeq For an accepted table status event, the table_status sync_seq it was recorded at. A snapshot at or past it already reflects the event.
	StatusSeq *int64 `json:"status_seq,omitempty"`

	// StockSeq For an accepted stock movement, the outlet_stock sync_seq of its product after the movement was applied. A snapshot at or past it already includes the movement.
	StockSeq *int64 `json:"stock_seq,omitempty"`
}

// PushResultCode defines model for PushResult.Code.
type PushResultCode string

// PushResultOutcome For an accepted table status event, whether the table took its status (applied) or kept a later change by another till (superseded).
type PushResultOutcome string

// PushResultStatus defines model for PushResult.Status.
type PushResultStatus string

// Register defines model for Register.
type Register struct {
	Id           ID     `json:"id"`
	Name         string `json:"name"`
	OutletId     ID     `json:"outlet_id"`
	TableService bool   `json:"table_service"`
}

// RegisterRow defines model for RegisterRow.
type RegisterRow struct {
	Active       bool   `json:"active"`
	DeletedAtMs  *int64 `json:"deleted_at_ms"`
	Id           string `json:"id"`
	Name         string `json:"name"`
	OutletId     string `json:"outlet_id"`
	SortOrder    int64  `json:"sort_order"`
	SyncSeq      int64  `json:"sync_seq"`
	TableService bool   `json:"table_service"`
}

// RoleRow A role. System roles (system_key set) take their permissions from the app's own table and publish an empty list; a custom role lists its permission names, comma-separated. A till drops names it does not know.
type RoleRow struct {
	BackofficeAccess bool    `json:"backoffice_access"`
	DeletedAtMs      *int64  `json:"deleted_at_ms"`
	Id               string  `json:"id"`
	Name             string  `json:"name"`
	Permissions      string  `json:"permissions"`
	PosAccess        bool    `json:"pos_access"`
	SortOrder        int64   `json:"sort_order"`
	SyncSeq          int64   `json:"sync_seq"`
	SystemKey        *string `json:"system_key"`
}

// SalesTypeRow defines model for SalesTypeRow.
type SalesTypeRow struct {
	Active      bool    `json:"active"`
	DeletedAtMs *int64  `json:"deleted_at_ms"`
	Id          string  `json:"id"`
	Name        string  `json:"name"`
	SortOrder   int64   `json:"sort_order"`
	SyncSeq     int64   `json:"sync_seq"`
	SystemKey   *string `json:"system_key"`
	UsesTable   bool    `json:"uses_table"`
}

// ServerTime defines model for ServerTime.
type ServerTime struct {
	ServerTimeMs Millis `json:"server_time_ms"`
}

// Session defines model for Session.
type Session struct {
	ClosedAtMs   *int64  `json:"closed_at_ms,omitempty"`
	ClosedById   *string `json:"closed_by_id,omitempty"`
	ClosedByName *string `json:"closed_by_name,omitempty"`
	CountedCash  *int64  `json:"counted_cash,omitempty"`
	EmployeeId   *string `json:"employee_id,omitempty"`
	EmployeeName Name    `json:"employee_name"`
	ExpectedCash *int64  `json:"expected_cash,omitempty"`
	Id           UUID    `json:"id"`
	Note         *string `json:"note,omitempty"`
	OpenedAtMs   Millis  `json:"opened_at_ms"`
	OpeningCash  Money   `json:"opening_cash"`

	// OrderCount Required when closing an online-claimed session. Number of durably recorded receipts in the drawer.
	OrderCount *int64  `json:"order_count,omitempty"`
	OutletName *string `json:"outlet_name,omitempty"`
	PosName    *string `json:"pos_name,omitempty"`
	Revision   int64   `json:"revision"`
}

// StockMovement One immutable ledger movement, applied at the token's outlet. delta_qty
// is signed: sale and waste negative, voidReturn and received positive,
// correction and opening non-zero. A count carries counted_qty; the server
// replaces its delta_qty with counted_qty minus the server's current
// quantity (server wins). An exact retry, including one at a newer
// revision, is accepted with the originally recorded result.
type StockMovement struct {
	BasisSeq     *int64              `json:"basis_seq,omitempty"`
	CountedQty   *int64              `json:"counted_qty,omitempty"`
	DeltaQty     int64               `json:"delta_qty"`
	EmployeeId   *string             `json:"employee_id,omitempty"`
	EmployeeName string              `json:"employee_name"`
	Id           UUID                `json:"id"`
	Note         *string             `json:"note,omitempty"`
	OccurredAtMs Millis              `json:"occurred_at_ms"`
	ProductId    UUID                `json:"product_id"`
	ProductName  string              `json:"product_name"`
	Reason       StockMovementReason `json:"reason"`
	Revision     int64               `json:"revision"`
}

// StockMovementReason defines model for StockMovement.Reason.
type StockMovementReason string

// StockMovementRow defines model for StockMovementRow.
type StockMovementRow struct {
	BalanceAfter int64   `json:"balance_after"`
	CountedQty   *int64  `json:"counted_qty"`
	DeletedAtMs  *int64  `json:"deleted_at_ms"`
	DeltaQty     int64   `json:"delta_qty"`
	EmployeeName string  `json:"employee_name"`
	Id           string  `json:"id"`
	Note         *string `json:"note"`
	OccurredAtMs int64   `json:"occurred_at_ms"`
	OutletId     string  `json:"outlet_id"`
	ProductId    string  `json:"product_id"`
	ProductName  string  `json:"product_name"`
	Reason       string  `json:"reason"`
	Source       string  `json:"source"`
	StockSeq     int64   `json:"stock_seq"`
	SyncSeq      int64   `json:"sync_seq"`
}

// TableRow defines model for TableRow.
type TableRow struct {
	Active      bool   `json:"active"`
	Area        string `json:"area"`
	Capacity    int64  `json:"capacity"`
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	OutletId    string `json:"outlet_id"`
	PosX        *int64 `json:"pos_x"`
	PosY        *int64 `json:"pos_y"`
	SortOrder   int64  `json:"sort_order"`
	SyncSeq     int64  `json:"sync_seq"`
}

// TableSession defines model for TableSession.
type TableSession struct {
	ClosedAtMs    *int64  `json:"closed_at_ms,omitempty"`
	ClosedByName  *string `json:"closed_by_name,omitempty"`
	GuestCount    *int    `json:"guest_count,omitempty"`
	Id            UUID    `json:"id"`
	OpenBillCount int     `json:"open_bill_count"`
	OpenedAtMs    Millis  `json:"opened_at_ms"`
	OpenedByName  string  `json:"opened_by_name"`
	TableId       UUID    `json:"table_id"`
	TableName     string  `json:"table_name"`
}

// TableSessionOpenRequest defines model for TableSessionOpenRequest.
type TableSessionOpenRequest struct {
	GuestCount *int `json:"guest_count,omitempty"`
	Id         UUID `json:"id"`
	TableId    UUID `json:"table_id"`
}

// TableSessionResponse defines model for TableSessionResponse.
type TableSessionResponse struct {
	Data TableSession `json:"data"`
}

// TableStatusEvent One immutable change of a table's live status, applied at the token's
// outlet. basis_seq is the table_status sync_seq the till had pulled for
// the table when it made the change (0 if it had none). An event made
// against the current sequence, or following the same device's own latest
// write, applies. One that raced another till's write is applied or
// superseded by occurred_at_ms (the event id breaks a tie) and marks the
// table contested; the next uncontested change clears the mark. An exact
// retry, including one at a newer revision, is accepted with the
// originally recorded result. client_seq orders this device's events even
// across clock corrections or reordered delivery; an older number is
// recorded as superseded. Tills number events max(previous + 1, wall-clock
// milliseconds), so a store reinstalled under the same device never reuses
// a number. A basis_seq ahead of the current table projection is refused.
type TableStatusEvent struct {
	BasisSeq int64 `json:"basis_seq"`

	// ClientSeq Monotonic per-device per-table event number, persisted offline. Older events never undo a later event from the same device.
	ClientSeq    int64                  `json:"client_seq"`
	EmployeeName string                 `json:"employee_name"`
	Id           UUID                   `json:"id"`
	OccurredAtMs Millis                 `json:"occurred_at_ms"`
	Revision     int64                  `json:"revision"`
	Status       TableStatusEventStatus `json:"status"`
	TableId      UUID                   `json:"table_id"`
}

// TableStatusEventStatus defines model for TableStatusEvent.Status.
type TableStatusEventStatus string

// TableStatusRow defines model for TableStatusRow.
type TableStatusRow struct {
	Contested    bool   `json:"contested"`
	DeletedAtMs  *int64 `json:"deleted_at_ms"`
	EmployeeName string `json:"employee_name"`
	OccurredAtMs int64  `json:"occurred_at_ms"`
	OutletId     string `json:"outlet_id"`
	Status       string `json:"status"`
	SyncSeq      int64  `json:"sync_seq"`
	TableId      string `json:"table_id"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	Id   ID     `json:"id"`
	Name string `json:"name"`

	// Timezone The merchant's trading clock (IANA name; the Backoffice offers Asia/Jakarta, Asia/Makassar and Asia/Jayapura). A till dates its receipts by it when it recognises the zone; absent from a server older than 2.8.0, and an unrecognised zone, both leave the device clock in charge as before.
	Timezone *string `json:"timezone,omitempty"`
}

// TillBillBoard defines model for TillBillBoard.
type TillBillBoard struct {
	Bills         []TillBillSummary `json:"bills"`
	ServerTimeMs  Millis            `json:"server_time_ms"`
	TableSessions []TableSession    `json:"table_sessions"`
}

// TillBillBoardResponse defines model for TillBillBoardResponse.
type TillBillBoardResponse struct {
	Data TillBillBoard `json:"data"`
}

// TillBillDetail defines model for TillBillDetail.
type TillBillDetail struct {
	// Bill Fase 4. One bill as its owning till last saved it, at a revision. The
	// till numbers revisions itself and every save is a newer one; the server
	// keeps the last accepted snapshot and accepts an exact retry of it. The
	// snapshot is refused as bill_not_owned when this till is not the owner or
	// owner_generation is not the bill's current one; a line already
	// dispatched must appear unchanged in every later revision. status
	// cancelled is terminal and needs cancel; closed is never pushed — the
	// settling receipt closes the bill. Saving takes no money and moves no
	// stock.
	Bill       Bill                  `json:"bill"`
	Dispatches []TillDispatchSummary `json:"dispatches"`
	Summary    TillBillSummary       `json:"summary"`
}

// TillBillDetailResponse defines model for TillBillDetailResponse.
type TillBillDetailResponse struct {
	Data TillBillDetail `json:"data"`
}

// TillBillParkData defines model for TillBillParkData.
type TillBillParkData struct {
	BillId          UUID   `json:"bill_id"`
	OwnerGeneration int64  `json:"owner_generation"`
	ParkedAtMs      Millis `json:"parked_at_ms"`
}

// TillBillParkRequest defines model for TillBillParkRequest.
type TillBillParkRequest struct {
	ExpectedDispatches int   `json:"expected_dispatches"`
	ExpectedRevision   int64 `json:"expected_revision"`
	OperationId        UUID  `json:"operation_id"`
}

// TillBillParkResponse defines model for TillBillParkResponse.
type TillBillParkResponse struct {
	Data TillBillParkData `json:"data"`
}

// TillBillSummary defines model for TillBillSummary.
type TillBillSummary struct {
	CustomerName *string `json:"customer_name,omitempty"`

	// Dispatches How many of the bill's dispatches are at each kitchen status.
	Dispatches        map[string]int        `json:"dispatches"`
	Id                UUID                  `json:"id"`
	LineCount         int                   `json:"line_count"`
	Number            string                `json:"number"`
	OpenedAtMs        Millis                `json:"opened_at_ms"`
	OwnedByThisDevice bool                  `json:"owned_by_this_device"`
	OwnerDeviceLabel  *string               `json:"owner_device_label,omitempty"`
	OwnerGeneration   int64                 `json:"owner_generation"`
	OwnerRegisterName *string               `json:"owner_register_name,omitempty"`
	Parked            bool                  `json:"parked"`
	Revision          int64                 `json:"revision"`
	Status            TillBillSummaryStatus `json:"status"`
	Subtotal          Money                 `json:"subtotal"`
	TableName         *string               `json:"table_name,omitempty"`
	TableSessionId    *string               `json:"table_session_id,omitempty"`
	UpdatedAtMs       Millis                `json:"updated_at_ms"`
}

// TillBillSummaryStatus defines model for TillBillSummary.Status.
type TillBillSummaryStatus string

// TillCurrentResponse defines model for TillCurrentResponse.
type TillCurrentResponse struct {
	Data     *TillSessionData     `json:"data"`
	Recovery *TillRecoveryPointer `json:"recovery,omitempty"`
}

// TillDispatchSummary defines model for TillDispatchSummary.
type TillDispatchSummary struct {
	// Dispatch The dispatch exactly as it was accepted, at its current status and revision. A till that claims the bill keeps it, so it can report later kitchen progress for a batch another till sent — a status change must repeat the batch's lines and stock unchanged.
	Dispatch          *KitchenDispatch          `json:"dispatch,omitempty"`
	EmployeeName      string                    `json:"employee_name"`
	Id                UUID                      `json:"id"`
	LineIds           []UUID                    `json:"line_ids"`
	OccurredAtMs      Millis                    `json:"occurred_at_ms"`
	Revision          int64                     `json:"revision"`
	Status            TillDispatchSummaryStatus `json:"status"`
	StatusChangedAtMs Millis                    `json:"status_changed_at_ms"`
}

// TillDispatchSummaryStatus defines model for TillDispatchSummary.Status.
type TillDispatchSummaryStatus string

// TillHandoverRequest defines model for TillHandoverRequest.
type TillHandoverRequest struct {
	Id UUID `json:"id"`
}

// TillHistoryPage defines model for TillHistoryPage.
type TillHistoryPage struct {
	From string                   `json:"from"`
	Next string                   `json:"next"`
	Rows []map[string]interface{} `json:"rows"`

	// Scope What the server applied, which may be narrower than what was asked for.
	Scope        TillHistoryPageScope `json:"scope"`
	ServerTimeMs Millis               `json:"server_time_ms"`
	To           string               `json:"to"`
}

// TillHistoryPageScope What the server applied, which may be narrower than what was asked for.
type TillHistoryPageScope string

// TillHistoryResponse defines model for TillHistoryResponse.
type TillHistoryResponse struct {
	Data TillHistoryPage `json:"data"`
}

// TillLoginData defines model for TillLoginData.
type TillLoginData struct {
	ExpiresAtMs Millis `json:"expires_at_ms"`
	Token       string `json:"token"`
}

// TillLoginRequest defines model for TillLoginRequest.
type TillLoginRequest struct {
	EmployeeId UUID   `json:"employee_id"`
	Pin        string `json:"pin"`
}

// TillLoginResponse defines model for TillLoginResponse.
type TillLoginResponse struct {
	Data TillLoginData `json:"data"`
}

// TillOperationRequest defines model for TillOperationRequest.
type TillOperationRequest struct {
	OperationId UUID `json:"operation_id"`
}

// TillRecovery defines model for TillRecovery.
type TillRecovery struct {
	ForcedAtMs          Millis                           `json:"forced_at_ms"`
	Id                  UUID                             `json:"id"`
	Items               []TillRecoveryItem               `json:"items"`
	ReconciliationBasis *TillRecoveryReconciliationBasis `json:"reconciliation_basis,omitempty"`
	SessionId           UUID                             `json:"session_id"`
	Status              TillRecoveryStatus               `json:"status"`
}

// TillRecoveryReconciliationBasis defines model for TillRecovery.ReconciliationBasis.
type TillRecoveryReconciliationBasis string

// TillRecoveryStatus defines model for TillRecovery.Status.
type TillRecoveryStatus string

// TillRecoveryItem defines model for TillRecoveryItem.
type TillRecoveryItem struct {
	CreatedAtMs    Millis                 `json:"created_at_ms"`
	DecidedAtMs    *Millis                `json:"decided_at_ms,omitempty"`
	DecisionReason *string                `json:"decision_reason,omitempty"`
	Entity         string                 `json:"entity"`
	EntityId       UUID                   `json:"entity_id"`
	Id             UUID                   `json:"id"`
	Revision       int64                  `json:"revision"`
	Status         TillRecoveryItemStatus `json:"status"`
}

// TillRecoveryItemStatus defines model for TillRecoveryItem.Status.
type TillRecoveryItemStatus string

// TillRecoveryPointer defines model for TillRecoveryPointer.
type TillRecoveryPointer struct {
	ForcedAtMs Millis `json:"forced_at_ms"`
	Id         UUID   `json:"id"`
	SessionId  UUID   `json:"session_id"`
}

// TillRecoveryResponse defines model for TillRecoveryResponse.
type TillRecoveryResponse struct {
	Data TillRecovery `json:"data"`
}

// TillReport defines model for TillReport.
type TillReport struct {
	Adjustments *[]map[string]interface{} `json:"adjustments,omitempty"`

	// AnomalyCount Receipts whose own arithmetic does not close. Reported, never repaired.
	AnomalyCount        *int64                    `json:"anomaly_count,omitempty"`
	ByBrand             *[]map[string]interface{} `json:"by_brand,omitempty"`
	ByCashier           *[]map[string]interface{} `json:"by_cashier,omitempty"`
	ByCategory          *[]map[string]interface{} `json:"by_category,omitempty"`
	ByDay               *[]map[string]interface{} `json:"by_day,omitempty"`
	ByHour              *[]map[string]interface{} `json:"by_hour,omitempty"`
	ByOutlet            *[]map[string]interface{} `json:"by_outlet,omitempty"`
	ByPayment           *[]map[string]interface{} `json:"by_payment,omitempty"`
	ByProduct           *[]map[string]interface{} `json:"by_product,omitempty"`
	ByProductInCategory *[]map[string]interface{} `json:"by_product_in_category,omitempty"`

	// BySalesType Fase 3. Net sales and revenue per sales type.
	BySalesType *[]map[string]interface{} `json:"by_sales_type,omitempty"`

	// ByWeekday Derived from the business date, so a sale after midnight belongs to its trading day. weekday is 0 for Sunday.
	ByWeekday *[]map[string]interface{} `json:"by_weekday,omitempty"`

	// CalculationVersion Which rules produced these figures. 2 is the Fase 1 waterfall.
	CalculationVersion int `json:"calculation_version"`

	// ComputedAtMs Null when the range holds no computed rollup at all.
	ComputedAtMs *int64 `json:"computed_at_ms,omitempty"`

	// Incomplete True while some day in range is still computed under the old rules; the waterfall columns are not final.
	Incomplete bool `json:"incomplete"`

	// PendingSlices Day-outlet slices in range with changes not yet rolled up.
	PendingSlices int64            `json:"pending_slices"`
	Period        TillReportPeriod `json:"period"`

	// Profit Present only on /till/reports/sales. margin is null when there are no net sales to divide by.
	Profit *TillReportProfit `json:"profit,omitempty"`

	// Sales The waterfall, read top to bottom. net_sales = gross_sales - discounts - sales_returns; revenue = net_sales + tax + service_charge. gross_sales includes a receipt that was later refunded, and sales_returns takes it out again, so a refund is visible rather than the day silently shrinking. refunded_amount is the money handed back, which includes tax and is therefore not the same number as sales_returns. cancelled_amount is shown separately and is never subtracted from the waterfall.
	Sales        TillReportSales `json:"sales"`
	Scope        TillReportScope `json:"scope"`
	ServerTimeMs Millis          `json:"server_time_ms"`
	Timezone     string          `json:"timezone"`
}

// TillReportPeriod defines model for TillReportPeriod.
type TillReportPeriod struct {
	Days int    `json:"days"`
	From string `json:"from"`
	To   string `json:"to"`
}

// TillReportProfit Present only on /till/reports/sales. margin is null when there are no net sales to divide by.
type TillReportProfit struct {
	CostCoverage float64  `json:"cost_coverage"`
	CostOfGoods  Money    `json:"cost_of_goods"`
	GrossProfit  int64    `json:"gross_profit"`
	Margin       *float64 `json:"margin,omitempty"`
}

// TillReportResponse defines model for TillReportResponse.
type TillReportResponse struct {
	Data TillReport `json:"data"`
}

// TillReportSales The waterfall, read top to bottom. net_sales = gross_sales - discounts - sales_returns; revenue = net_sales + tax + service_charge. gross_sales includes a receipt that was later refunded, and sales_returns takes it out again, so a refund is visible rather than the day silently shrinking. refunded_amount is the money handed back, which includes tax and is therefore not the same number as sales_returns. cancelled_amount is shown separately and is never subtracted from the waterfall.
type TillReportSales struct {
	AverageSale     Money  `json:"average_sale"`
	CancelledAmount *Money `json:"cancelled_amount,omitempty"`
	CancelledCount  *int64 `json:"cancelled_count,omitempty"`
	Discounted      *int64 `json:"discounted,omitempty"`
	Discounts       Money  `json:"discounts"`
	GrossSales      Money  `json:"gross_sales"`
	ItemsSold       int64  `json:"items_sold"`
	NetSales        Money  `json:"net_sales"`
	OrderCount      int64  `json:"order_count"`
	RefundedAmount  *Money `json:"refunded_amount,omitempty"`
	RefundedCount   *int64 `json:"refunded_count,omitempty"`
	Revenue         Money  `json:"revenue"`

	// Rounding Fase 3. Final rounding collected (may be negative); part of revenue, never of sales.
	Rounding      *int64 `json:"rounding,omitempty"`
	SalesReturns  Money  `json:"sales_returns"`
	ServiceCharge Money  `json:"service_charge"`
	Tax           Money  `json:"tax"`

	// TaxIncluded Fase 3. Tax already inside inclusive prices; taken out of net sales, so gross - discounts - sales_returns - tax_included = net_sales.
	TaxIncluded *Money `json:"tax_included,omitempty"`
}

// TillReportScope defines model for TillReportScope.
type TillReportScope struct {
	AllOutlets bool   `json:"all_outlets"`
	OutletId   string `json:"outlet_id"`
	OutletName string `json:"outlet_name"`
}

// TillSessionData defines model for TillSessionData.
type TillSessionData struct {
	CurrentEmployeeId *UUID   `json:"current_employee_id,omitempty"`
	ReceiptEnd        int64   `json:"receipt_end"`
	ReceiptStart      int64   `json:"receipt_start"`
	Session           Session `json:"session"`
}

// TillSessionResponse defines model for TillSessionResponse.
type TillSessionResponse struct {
	Data TillSessionData `json:"data"`
}

// UUID defines model for UUID.
type UUID = string

// VariantRow defines model for VariantRow.
type VariantRow struct {
	DeletedAtMs *int64 `json:"deleted_at_ms"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	PriceDelta  int64  `json:"price_delta"`
	ProductId   string `json:"product_id"`
	SortOrder   int64  `json:"sort_order"`
	SyncSeq     int64  `json:"sync_seq"`
}

// CashierToken defines model for CashierToken.
type CashierToken = string

// DeviceCapabilities defines model for DeviceCapabilities.
type DeviceCapabilities = string

// ReportFrom defines model for ReportFrom.
type ReportFrom = string

// ReportOutlet defines model for ReportOutlet.
type ReportOutlet = string

// ReportPeriod defines model for ReportPeriod.
type ReportPeriod string

// ReportTo defines model for ReportTo.
type ReportTo = string

// SchemaVersion defines model for SchemaVersion.
type SchemaVersion = int

// Error defines model for Error.
type Error = ErrorResponse

// ActivateDeviceParams defines parameters for ActivateDevice.
type ActivateDeviceParams struct {
	// XDeviceCapabilities Comma-separated feature tokens this build honours (pricing-v2, roles-v1, bills-v1). Recorded per device only when the set changes; unknown tokens are ignored. Absent means an app older than Fase 3, which is exactly what the Backoffice needs to know before it enables a feature.
	XDeviceCapabilities *DeviceCapabilities `json:"X-Device-Capabilities,omitempty"`
}

// GetDeviceParams defines parameters for GetDevice.
type GetDeviceParams struct {
	// XDeviceCapabilities Comma-separated feature tokens this build honours (pricing-v2, roles-v1, bills-v1). Recorded per device only when the set changes; unknown tokens are ignored. Absent means an app older than Fase 3, which is exactly what the Backoffice needs to know before it enables a feature.
	XDeviceCapabilities *DeviceCapabilities `json:"X-Device-Capabilities,omitempty"`
}

// GetChangesParams defines parameters for GetChanges.
type GetChangesParams struct {
	// XSchemaVersion Missing/obsolete returns 409 device_schema_outdated; invalid returns 400.
	XSchemaVersion SchemaVersion `json:"X-Schema-Version"`

	// XDeviceCapabilities Comma-separated feature tokens this build honours (pricing-v2, roles-v1, bills-v1). Recorded per device only when the set changes; unknown tokens are ignored. Absent means an app older than Fase 3, which is exactly what the Backoffice needs to know before it enables a feature.
	XDeviceCapabilities *DeviceCapabilities `json:"X-Device-Capabilities,omitempty"`
}

// GetManifestParams defines parameters for GetManifest.
type GetManifestParams struct {
	// XSchemaVersion Missing/obsolete returns 409 device_schema_outdated; invalid returns 400.
	XSchemaVersion SchemaVersion `json:"X-Schema-Version"`

	// XDeviceCapabilities Comma-separated feature tokens this build honours (pricing-v2, roles-v1, bills-v1). Recorded per device only when the set changes; unknown tokens are ignored. Absent means an app older than Fase 3, which is exactly what the Backoffice needs to know before it enables a feature.
	XDeviceCapabilities *DeviceCapabilities `json:"X-Device-Capabilities,omitempty"`
}

// PullChangesParams defines parameters for PullChanges.
type PullChangesParams struct {
	Entity   string `form:"entity" json:"entity"`
	AfterSeq *int64 `form:"after_seq,omitempty" json:"after_seq,omitempty"`
	Limit    *int   `form:"limit,omitempty" json:"limit,omitempty"`

	// XSchemaVersion Missing/obsolete returns 409 device_schema_outdated; invalid returns 400.
	XSchemaVersion SchemaVersion `json:"X-Schema-Version"`

	// XDeviceCapabilities Comma-separated feature tokens this build honours (pricing-v2, roles-v1, bills-v1). Recorded per device only when the set changes; unknown tokens are ignored. Absent means an app older than Fase 3, which is exactly what the Backoffice needs to know before it enables a feature.
	XDeviceCapabilities *DeviceCapabilities `json:"X-Device-Capabilities,omitempty"`
}

// PushChangesParams defines parameters for PushChanges.
type PushChangesParams struct {
	// XSchemaVersion Missing/obsolete returns 409 device_schema_outdated; invalid returns 400.
	XSchemaVersion SchemaVersion `json:"X-Schema-Version"`

	// XDeviceCapabilities Comma-separated feature tokens this build honours (pricing-v2, roles-v1, bills-v1). Recorded per device only when the set changes; unknown tokens are ignored. Absent means an app older than Fase 3, which is exactly what the Backoffice needs to know before it enables a feature.
	XDeviceCapabilities *DeviceCapabilities `json:"X-Device-Capabilities,omitempty"`
}

// TillBillBoardParams defines parameters for TillBillBoard.
type TillBillBoardParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// TillBillDetailParams defines parameters for TillBillDetail.
type TillBillDetailParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// ClaimTillBillParams defines parameters for ClaimTillBill.
type ClaimTillBillParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// ParkTillBillParams defines parameters for ParkTillBill.
type ParkTillBillParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// TillOrderHistoryParams defines parameters for TillOrderHistory.
type TillOrderHistoryParams struct {
	// Day One business date. Omitting every date filter means the current business date on the merchant's clock. Combining day with from or to is refused as ambiguous_range.
	Day *string `form:"day,omitempty" json:"day,omitempty"`

	// From First business date of a range; at most 366 days with to.
	From *string `form:"from,omitempty" json:"from,omitempty"`

	// To Last business date of a range.
	To *string `form:"to,omitempty" json:"to,omitempty"`

	// Scope Defaults to register. outlet needs viewAllOrders and is refused with forbidden_scope otherwise.
	Scope *TillOrderHistoryParamsScope `form:"scope,omitempty" json:"scope,omitempty"`

	// Status sales is every receipt that was not cancelled or refunded.
	Status *TillOrderHistoryParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// ReceiptNumber Case-insensitive prefix of the printed receipt number.
	ReceiptNumber *string `form:"receipt_number,omitempty" json:"receipt_number,omitempty"`

	// CashierId A cashier may only name themselves; anything else needs viewAllOrders and is refused with forbidden_cashier.
	CashierId *UUID `form:"cashier_id,omitempty" json:"cashier_id,omitempty"`

	// Before Opaque cursor returned by the previous page. Bound to the filter it was issued for; a cursor from an older contract is refused with invalid_cursor.
	Before *string `form:"before,omitempty" json:"before,omitempty"`

	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// TillOrderHistoryParamsScope defines parameters for TillOrderHistory.
type TillOrderHistoryParamsScope string

// TillOrderHistoryParamsStatus defines parameters for TillOrderHistory.
type TillOrderHistoryParamsStatus string

// GetTillRecoveryParams defines parameters for GetTillRecovery.
type GetTillRecoveryParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// TillReportSalesParams defines parameters for TillReportSales.
type TillReportSalesParams struct {
	// Period Resolved on the merchant's clock. Omitted with from and to present means custom; omitted entirely means today. An unknown value falls back to today rather than failing, because a dashboard is a glance.
	Period *TillReportSalesParamsPeriod `form:"period,omitempty" json:"period,omitempty"`

	// From First business date; used only with period=custom. At most 366 days with to.
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`

	// To Last business date; used only with period=custom.
	To *ReportTo `form:"to,omitempty" json:"to,omitempty"`

	// OutletId The device's own outlet when omitted. Another outlet, or the literal "all" for every outlet, needs manageOutlets; otherwise the request is refused rather than narrowed, so a total is never quietly one branch.
	OutletId *ReportOutlet `form:"outlet_id,omitempty" json:"outlet_id,omitempty"`

	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// TillReportSalesParamsPeriod defines parameters for TillReportSales.
type TillReportSalesParamsPeriod string

// TillReportSummaryParams defines parameters for TillReportSummary.
type TillReportSummaryParams struct {
	// Period Resolved on the merchant's clock. Omitted with from and to present means custom; omitted entirely means today. An unknown value falls back to today rather than failing, because a dashboard is a glance.
	Period *TillReportSummaryParamsPeriod `form:"period,omitempty" json:"period,omitempty"`

	// From First business date; used only with period=custom. At most 366 days with to.
	From *ReportFrom `form:"from,omitempty" json:"from,omitempty"`

	// To Last business date; used only with period=custom.
	To *ReportTo `form:"to,omitempty" json:"to,omitempty"`

	// OutletId The device's own outlet when omitted. Another outlet, or the literal "all" for every outlet, needs manageOutlets; otherwise the request is refused rather than narrowed, so a total is never quietly one branch.
	OutletId *ReportOutlet `form:"outlet_id,omitempty" json:"outlet_id,omitempty"`

	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// TillReportSummaryParamsPeriod defines parameters for TillReportSummary.
type TillReportSummaryParamsPeriod string

// CurrentTillSessionParams defines parameters for CurrentTillSession.
type CurrentTillSessionParams struct {
	// LocalSessionId Locally active session used only to discover a matching forced recovery.
	LocalSessionId *UUID `form:"local_session_id,omitempty" json:"local_session_id,omitempty"`

	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// HandoverTillSessionParams defines parameters for HandoverTillSession.
type HandoverTillSessionParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// OpenTillSessionParams defines parameters for OpenTillSession.
type OpenTillSessionParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// OpenTableSessionParams defines parameters for OpenTableSession.
type OpenTableSessionParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// CloseTableSessionParams defines parameters for CloseTableSession.
type CloseTableSessionParams struct {
	// XCashierToken Short-lived cashier credential returned by POST /till/login.
	XCashierToken CashierToken `json:"X-Cashier-Token"`
}

// ActivateDeviceJSONRequestBody defines body for ActivateDevice for application/json ContentType.
type ActivateDeviceJSONRequestBody = ActivateRequest

// PushChangesJSONRequestBody defines body for PushChanges for application/json ContentType.
type PushChangesJSONRequestBody = PushRequest

// ClaimTillBillJSONRequestBody defines body for ClaimTillBill for application/json ContentType.
type ClaimTillBillJSONRequestBody = TillOperationRequest

// ParkTillBillJSONRequestBody defines body for ParkTillBill for application/json ContentType.
type ParkTillBillJSONRequestBody = TillBillParkRequest

// TillLoginJSONRequestBody defines body for TillLogin for application/json ContentType.
type TillLoginJSONRequestBody = TillLoginRequest

// HandoverTillSessionJSONRequestBody defines body for HandoverTillSession for application/json ContentType.
type HandoverTillSessionJSONRequestBody = TillHandoverRequest

// OpenTillSessionJSONRequestBody defines body for OpenTillSession for application/json ContentType.
type OpenTillSessionJSONRequestBody = Session

// OpenTableSessionJSONRequestBody defines body for OpenTableSession for application/json ContentType.
type OpenTableSessionJSONRequestBody = TableSessionOpenRequest

// CloseTableSessionJSONRequestBody defines body for CloseTableSession for application/json ContentType.
type CloseTableSessionJSONRequestBody = TillOperationRequest
