// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: counters.sql

package store

import (
	"context"
)

const allocateSyncBlock = `-- name: AllocateSyncBlock :one
INSERT INTO sync_counters (scope_key, tenant_id, last_seq)
VALUES ($1, $2, $3)
ON CONFLICT (scope_key) DO UPDATE SET last_seq = sync_counters.last_seq + EXCLUDED.last_seq
RETURNING last_seq
`

type AllocateSyncBlockParams struct {
	ScopeKey string
	TenantID string
	LastSeq  int64
}

func (q *Queries) AllocateSyncBlock(ctx context.Context, arg AllocateSyncBlockParams) (int64, error) {
	row := q.db.QueryRow(ctx, allocateSyncBlock, arg.ScopeKey, arg.TenantID, arg.LastSeq)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const readSyncCounter = `-- name: ReadSyncCounter :one
SELECT last_seq FROM sync_counters WHERE scope_key = $1
`

func (q *Queries) ReadSyncCounter(ctx context.Context, scopeKey string) (int64, error) {
	row := q.db.QueryRow(ctx, readSyncCounter, scopeKey)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const readSyncCounters = `-- name: ReadSyncCounters :many
SELECT scope_key, last_seq FROM sync_counters WHERE tenant_id = $1
`

type ReadSyncCountersRow struct {
	ScopeKey string
	LastSeq  int64
}

func (q *Queries) ReadSyncCounters(ctx context.Context, tenantID string) ([]ReadSyncCountersRow, error) {
	rows, err := q.db.Query(ctx, readSyncCounters, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadSyncCountersRow{}
	for rows.Next() {
		var i ReadSyncCountersRow
		if err := rows.Scan(&i.ScopeKey, &i.LastSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readSyncCountersByKeys = `-- name: ReadSyncCountersByKeys :many
SELECT scope_key, last_seq FROM sync_counters WHERE scope_key = ANY($1::text[])
`

type ReadSyncCountersByKeysRow struct {
	ScopeKey string
	LastSeq  int64
}

func (q *Queries) ReadSyncCountersByKeys(ctx context.Context, scopeKeys []string) ([]ReadSyncCountersByKeysRow, error) {
	rows, err := q.db.Query(ctx, readSyncCountersByKeys, scopeKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadSyncCountersByKeysRow{}
	for rows.Next() {
		var i ReadSyncCountersByKeysRow
		if err := rows.Scan(&i.ScopeKey, &i.LastSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
