// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendIngestLog = `-- name: AppendIngestLog :exec
INSERT INTO ingest_log (tenant_id, device_id, entity, payload)
VALUES ($1, $2, $3, $4)
`

type AppendIngestLogParams struct {
	TenantID string
	DeviceID string
	Entity   string
	Payload  []byte
}

func (q *Queries) AppendIngestLog(ctx context.Context, arg AppendIngestLogParams) error {
	_, err := q.db.Exec(ctx, appendIngestLog,
		arg.TenantID,
		arg.DeviceID,
		arg.Entity,
		arg.Payload,
	)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT business_date, id, tenant_id, outlet_id, pos_register_id, device_id, pos_session_id, revision, status, settled_at, placed_at_ms, subtotal, discount, tax, service_charge_amount, total, amount_paid, refunded_amount, payment_method, cashier_name, authorized_by, void_reason, payload, created_at, updated_at, customer_id, tax_included, rounding_amount, pricing_mismatch FROM orders WHERE business_date = $1 AND id = $2
`

type GetOrderParams struct {
	BusinessDate pgtype.Date
	ID           string
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.BusinessDate, arg.ID)
	var i Order
	err := row.Scan(
		&i.BusinessDate,
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.PosRegisterID,
		&i.DeviceID,
		&i.PosSessionID,
		&i.Revision,
		&i.Status,
		&i.SettledAt,
		&i.PlacedAtMs,
		&i.Subtotal,
		&i.Discount,
		&i.Tax,
		&i.ServiceChargeAmount,
		&i.Total,
		&i.AmountPaid,
		&i.RefundedAmount,
		&i.PaymentMethod,
		&i.CashierName,
		&i.AuthorizedBy,
		&i.VoidReason,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.TaxIncluded,
		&i.RoundingAmount,
		&i.PricingMismatch,
	)
	return i, err
}

const getOrderReservation = `-- name: GetOrderReservation :one
SELECT id, tenant_id, outlet_id, pos_register_id, device_id, business_date, first_seen FROM order_dedupe WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOrderReservation(ctx context.Context, id string) (OrderDedupe, error) {
	row := q.db.QueryRow(ctx, getOrderReservation, id)
	var i OrderDedupe
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.PosRegisterID,
		&i.DeviceID,
		&i.BusinessDate,
		&i.FirstSeen,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, tenant_id, outlet_id, pos_register_id, device_id, revision, employee_name, opened_at_ms, closed_at_ms, opening_cash, counted_cash, expected_cash, payload, created_at, updated_at, close_kind, forced_recovery_id FROM pos_sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, id string) (PosSession, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, id)
	var i PosSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OutletID,
		&i.PosRegisterID,
		&i.DeviceID,
		&i.Revision,
		&i.EmployeeName,
		&i.OpenedAtMs,
		&i.ClosedAtMs,
		&i.OpeningCash,
		&i.CountedCash,
		&i.ExpectedCash,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloseKind,
		&i.ForcedRecoveryID,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO orders (business_date, id, tenant_id, outlet_id, pos_register_id, device_id, pos_session_id,
 revision, status, settled_at, placed_at_ms, subtotal, discount, tax, service_charge_amount,
 total, amount_paid, refunded_amount, payment_method, cashier_name, authorized_by, void_reason, customer_id,
 tax_included, rounding_amount, pricing_mismatch, payload)
SELECT $1, (p->>'id')::uuid, $2, $3, $4, $5, (p->>'pos_session_id')::uuid,
 (p->>'revision')::bigint, p->>'status', CASE WHEN p->>'status' IN ('cancelled','refunded') THEN now() END,
 (p->>'placed_at_ms')::bigint, (p->>'subtotal')::bigint, (p->>'discount')::bigint, (p->>'tax')::bigint,
 (p->>'service_charge_amount')::bigint, (p->>'total')::bigint, (p->>'amount_paid')::bigint,
 (p->>'refunded_amount')::bigint, p->>'payment_method', p->>'cashier_name', p->>'authorized_by', p->>'void_reason',
 NULLIF(p->>'customer_id', '')::uuid,
 COALESCE((p->>'tax_included')::bigint, 0), COALESCE((p->>'rounding_amount')::bigint, 0), $7, p
FROM (SELECT $6::jsonb AS p) input
`

type InsertOrderParams struct {
	BusinessDate    pgtype.Date
	TenantID        string
	OutletID        string
	PosRegisterID   string
	DeviceID        string
	Column6         []byte
	PricingMismatch bool
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.BusinessDate,
		arg.TenantID,
		arg.OutletID,
		arg.PosRegisterID,
		arg.DeviceID,
		arg.Column6,
		arg.PricingMismatch,
	)
	return err
}

const insertOrderItems = `-- name: InsertOrderItems :exec
INSERT INTO order_items (business_date, id, tenant_id, order_id, product_name, category_name,
 unit_price, unit_cost, quantity, payload)
SELECT $1, (p->>'id')::uuid, $2, $3, p->>'product_name', p->>'category_name',
 (p->>'unit_price')::bigint, (p->>'unit_cost')::bigint, (p->>'quantity')::bigint, p
FROM jsonb_array_elements($4::jsonb) p
`

type InsertOrderItemsParams struct {
	BusinessDate pgtype.Date
	TenantID     string
	OrderID      string
	Column4      []byte
}

func (q *Queries) InsertOrderItems(ctx context.Context, arg InsertOrderItemsParams) error {
	_, err := q.db.Exec(ctx, insertOrderItems,
		arg.BusinessDate,
		arg.TenantID,
		arg.OrderID,
		arg.Column4,
	)
	return err
}

const insertOrderModifiers = `-- name: InsertOrderModifiers :exec
INSERT INTO order_item_modifiers (business_date, id, tenant_id, order_item_id, group_name, option_name, price_delta, sort_order)
SELECT $1, (m->>'id')::uuid, $2, (p->>'id')::uuid, m->>'group_name', m->>'option_name',
 (m->>'price_delta')::bigint, (m->>'sort_order')::integer
FROM jsonb_array_elements($3::jsonb) p CROSS JOIN LATERAL jsonb_array_elements(p->'modifiers') m
`

type InsertOrderModifiersParams struct {
	BusinessDate pgtype.Date
	TenantID     string
	Column3      []byte
}

func (q *Queries) InsertOrderModifiers(ctx context.Context, arg InsertOrderModifiersParams) error {
	_, err := q.db.Exec(ctx, insertOrderModifiers, arg.BusinessDate, arg.TenantID, arg.Column3)
	return err
}

const insertSession = `-- name: InsertSession :execrows
INSERT INTO pos_sessions (id, tenant_id, outlet_id, pos_register_id, device_id, revision,
 employee_name, opened_at_ms, closed_at_ms, opening_cash, counted_cash, expected_cash, payload)
SELECT (p->>'id')::uuid, $1, $2, $3, $4, (p->>'revision')::bigint,
 p->>'employee_name', (p->>'opened_at_ms')::bigint, (p->>'closed_at_ms')::bigint,
 (p->>'opening_cash')::bigint, (p->>'counted_cash')::bigint, (p->>'expected_cash')::bigint, p
FROM (SELECT $5::jsonb AS p) input
ON CONFLICT (id) DO NOTHING
`

type InsertSessionParams struct {
	TenantID      string
	OutletID      string
	PosRegisterID string
	DeviceID      string
	Column5       []byte
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSession,
		arg.TenantID,
		arg.OutletID,
		arg.PosRegisterID,
		arg.DeviceID,
		arg.Column5,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markReportDirty = `-- name: MarkReportDirty :exec
INSERT INTO report_dirty_slices (tenant_id, outlet_id, business_date) VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, outlet_id, business_date) DO UPDATE
SET generation = report_dirty_slices.generation + 1, changed_at = now()
`

type MarkReportDirtyParams struct {
	TenantID     string
	OutletID     string
	BusinessDate pgtype.Date
}

func (q *Queries) MarkReportDirty(ctx context.Context, arg MarkReportDirtyParams) error {
	_, err := q.db.Exec(ctx, markReportDirty, arg.TenantID, arg.OutletID, arg.BusinessDate)
	return err
}

const openSessionHolder = `-- name: OpenSessionHolder :one
SELECT id, employee_name FROM pos_sessions WHERE pos_register_id = $1 AND closed_at_ms IS NULL
`

type OpenSessionHolderRow struct {
	ID           string
	EmployeeName string
}

func (q *Queries) OpenSessionHolder(ctx context.Context, posRegisterID string) (OpenSessionHolderRow, error) {
	row := q.db.QueryRow(ctx, openSessionHolder, posRegisterID)
	var i OpenSessionHolderRow
	err := row.Scan(&i.ID, &i.EmployeeName)
	return i, err
}

const reserveOrderID = `-- name: ReserveOrderID :execrows
INSERT INTO order_dedupe (id, tenant_id, outlet_id, pos_register_id, device_id, business_date)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (id) DO NOTHING
`

type ReserveOrderIDParams struct {
	ID            string
	TenantID      string
	OutletID      string
	PosRegisterID string
	DeviceID      string
	BusinessDate  pgtype.Date
}

func (q *Queries) ReserveOrderID(ctx context.Context, arg ReserveOrderIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveOrderID,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.PosRegisterID,
		arg.DeviceID,
		arg.BusinessDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOpenSession = `-- name: UpdateOpenSession :execrows
UPDATE pos_sessions SET revision = (p->>'revision')::bigint,
 closed_at_ms = (p->>'closed_at_ms')::bigint, counted_cash = (p->>'counted_cash')::bigint,
 expected_cash = (p->>'expected_cash')::bigint, payload = p, updated_at = now()
FROM (SELECT $2::jsonb AS p) input
WHERE pos_sessions.id = $1 AND closed_at_ms IS NULL AND revision < (p->>'revision')::bigint
`

type UpdateOpenSessionParams struct {
	ID      string
	Column2 []byte
}

func (q *Queries) UpdateOpenSession(ctx context.Context, arg UpdateOpenSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOpenSession, arg.ID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUnsettledOrder = `-- name: UpdateUnsettledOrder :execrows
UPDATE orders SET revision = (p->>'revision')::bigint, status = p->>'status',
 settled_at = CASE WHEN p->>'status' IN ('cancelled','refunded') THEN now() END,
 refunded_amount = (p->>'refunded_amount')::bigint, authorized_by = p->>'authorized_by',
 void_reason = p->>'void_reason', payload = p, updated_at = now()
FROM (SELECT $3::jsonb AS p) input
WHERE business_date = $1 AND orders.id = $2 AND settled_at IS NULL AND revision < (p->>'revision')::bigint
`

type UpdateUnsettledOrderParams struct {
	BusinessDate pgtype.Date
	ID           string
	Column3      []byte
}

func (q *Queries) UpdateUnsettledOrder(ctx context.Context, arg UpdateUnsettledOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUnsettledOrder, arg.BusinessDate, arg.ID, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
