// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivationCode struct {
	ID                 string
	TenantID           string
	OutletID           string
	PosRegisterID      string
	Fingerprint        []byte
	ExpiresAt          pgtype.Timestamptz
	ConsumedAt         pgtype.Timestamptz
	CancelledAt        pgtype.Timestamptz
	IssuedByEmployeeID pgtype.UUID
	DeviceID           pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

type Category struct {
	ID        string
	TenantID  string
	Name      string
	IconKey   pgtype.Text
	SortOrder int32
	IsPopular bool
	SyncSeq   int64
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Device struct {
	ID             string
	TenantID       string
	OutletID       string
	PosRegisterID  string
	DeviceUuid     string
	Label          pgtype.Text
	Platform       pgtype.Text
	TokenSha256    []byte
	TokenExpiresAt pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Employee struct {
	ID        string
	TenantID  string
	Name      string
	Email     pgtype.Text
	Password  pgtype.Text
	PinHash   pgtype.Text
	Role      string
	Active    bool
	SortOrder int32
	SyncSeq   int64
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type IngestLog struct {
	ReceivedDate pgtype.Date
	ID           string
	TenantID     string
	DeviceID     string
	Entity       string
	Payload      []byte
	ReceivedAt   pgtype.Timestamptz
}

type ModifierGroup struct {
	ID            string
	TenantID      string
	Name          string
	SelectionType string
	Required      bool
	MaxSelect     pgtype.Int4
	SortOrder     int32
	Active        bool
	SyncSeq       int64
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ModifierOption struct {
	ID         string
	TenantID   string
	GroupID    string
	Name       string
	PriceDelta int64
	SortOrder  int32
	Active     bool
	SyncSeq    int64
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Order struct {
	BusinessDate        pgtype.Date
	ID                  string
	TenantID            string
	OutletID            string
	PosRegisterID       string
	DeviceID            string
	PosSessionID        string
	Revision            int64
	Status              string
	SettledAt           pgtype.Timestamptz
	PlacedAtMs          int64
	Subtotal            int64
	Discount            int64
	Tax                 int64
	ServiceChargeAmount int64
	Total               int64
	AmountPaid          int64
	RefundedAmount      pgtype.Int8
	PaymentMethod       string
	CashierName         string
	AuthorizedBy        pgtype.Text
	VoidReason          pgtype.Text
	Payload             []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type OrderDedupe struct {
	ID            string
	TenantID      string
	OutletID      string
	PosRegisterID string
	DeviceID      string
	BusinessDate  pgtype.Date
	FirstSeen     pgtype.Timestamptz
}

type OrderItem struct {
	BusinessDate pgtype.Date
	ID           string
	TenantID     string
	OrderID      string
	ProductName  string
	CategoryName pgtype.Text
	UnitPrice    int64
	UnitCost     pgtype.Int8
	Quantity     int64
	Payload      []byte
}

type OrderItemModifier struct {
	BusinessDate pgtype.Date
	ID           string
	TenantID     string
	OrderItemID  string
	GroupName    string
	OptionName   string
	PriceDelta   int64
	SortOrder    int32
}

type Outlet struct {
	ID             string
	TenantID       string
	Name           string
	Address        pgtype.Text
	Phone          pgtype.Text
	Active         bool
	SortOrder      int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	SyncSeq        int64
	DeletedAt      pgtype.Timestamptz
	AuthGeneration int64
}

type OutletStock struct {
	TenantID  string
	OutletID  string
	ProductID string
	QtyOnHand int64
	SyncSeq   int64
	DeletedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PosRegister struct {
	ID             string
	TenantID       string
	OutletID       string
	Name           string
	TableService   bool
	Active         bool
	SortOrder      int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	SyncSeq        int64
	DeletedAt      pgtype.Timestamptz
	AuthGeneration int64
}

type PosSession struct {
	ID            string
	TenantID      string
	OutletID      string
	PosRegisterID string
	DeviceID      string
	Revision      int64
	EmployeeName  string
	OpenedAtMs    int64
	ClosedAtMs    pgtype.Int8
	OpeningCash   int64
	CountedCash   pgtype.Int8
	ExpectedCash  pgtype.Int8
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Product struct {
	ID          string
	TenantID    string
	CategoryID  string
	Name        string
	Price       int64
	Cost        pgtype.Int8
	Sku         pgtype.Text
	TaxRate     pgtype.Float8
	Description pgtype.Text
	ImageUrl    pgtype.Text
	IconKey     string
	Available   bool
	IsPopular   bool
	SortOrder   int32
	SyncSeq     int64
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ImageKey    pgtype.Text
}

type ProductModifierGroup struct {
	TenantID  string
	ProductID string
	GroupID   string
	SyncSeq   int64
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ProductModifierOption struct {
	TenantID  string
	ProductID string
	OptionID  string
	IsDefault bool
	SyncSeq   int64
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ProductVariant struct {
	ID         string
	TenantID   string
	ProductID  string
	Name       string
	PriceDelta int64
	SortOrder  int32
	SyncSeq    int64
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Promo struct {
	ID         string
	TenantID   string
	Name       string
	Kind       string
	Value      int64
	MinSpend   int64
	Active     bool
	SortOrder  int32
	SyncSeq    int64
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	AllOutlets bool
}

type PromoOutlet struct {
	TenantID  string
	PromoID   string
	OutletID  string
	SyncSeq   int64
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ReportDirtySlice struct {
	TenantID     string
	OutletID     string
	BusinessDate pgtype.Date
	Generation   int64
	ChangedAt    pgtype.Timestamptz
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type StockMovement struct {
	ID              string
	TenantID        string
	OutletID        string
	ProductID       string
	Reason          string
	DeltaQty        int64
	CountedQty      pgtype.Int8
	BasisSeq        pgtype.Int8
	BalanceAfter    int64
	OccurredAtMs    int64
	Source          string
	DeviceID        pgtype.UUID
	CreatedBy       pgtype.UUID
	EmployeeName    string
	ProductName     string
	Note            pgtype.Text
	RefType         pgtype.Text
	RefID           pgtype.UUID
	Payload         []byte
	AppliedStockSeq int64
	SyncSeq         int64
	DeletedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type SyncCounter struct {
	ScopeKey string
	TenantID string
	LastSeq  int64
}

type Table struct {
	ID        string
	TenantID  string
	OutletID  string
	Name      string
	Area      string
	Capacity  int32
	PosX      pgtype.Int4
	PosY      pgtype.Int4
	SortOrder int32
	Active    bool
	SyncSeq   int64
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TableStatus struct {
	TenantID     string
	TableID      string
	OutletID     string
	Status       string
	OccurredAtMs int64
	EventID      pgtype.UUID
	DeviceID     pgtype.UUID
	EmployeeName string
	Contested    bool
	SyncSeq      int64
	DeletedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type TableStatusEvent struct {
	ID           string
	TenantID     string
	OutletID     string
	TableID      string
	Status       string
	BasisSeq     int64
	ClientSeq    int64
	OccurredAtMs int64
	DeviceID     string
	EmployeeName string
	Outcome      string
	StatusSeq    int64
	Contested    bool
	Payload      []byte
	CreatedAt    pgtype.Timestamptz
}

type Tenant struct {
	ID             string
	Name           string
	Slug           string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AuthGeneration int64
}
