<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A physical tablet, bound to one register at one outlet.
 *
 * Entirely new infrastructure: the Flutter app has no device identity at all
 * today — a device is implicitly "whichever outlet and session this
 * SharedPreferences instance happens to hold". That is fine for one tablet with
 * one local database, and useless the moment a server has to decide whether an
 * incoming request is a till it knows.
 *
 * `device_uuid` is generated by the client and is what the tablet re-presents
 * after a reinstall. It is unique **per tenant**, not globally: it is
 * client-supplied, so a global unique index would let one merchant's device
 * block another merchant's activation by claiming the same string.
 *
 * Revoking sets `revoked_at` and deletes the Sanctum tokens. The row itself
 * stays — a stolen tablet is something an Owner needs to keep seeing.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('devices', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->foreignUuid('tenant_id')->constrained()->cascadeOnDelete();
            $table->foreignUuid('outlet_id')->constrained()->cascadeOnDelete();
            $table->foreignUuid('pos_register_id')->constrained()->cascadeOnDelete();

            $table->string('device_uuid');
            $table->string('label')->nullable();
            $table->string('platform')->nullable();

            // Observability for the Backoffice: "is the till in Kemang actually
            // talking to us?" is a question an Owner asks before a sync bug is
            // ever reported as one.
            $table->timestamp('last_seen_at')->nullable();
            $table->timestamp('revoked_at')->nullable();

            $table->timestamps();

            $table->unique(['tenant_id', 'device_uuid']);
            $table->index(['tenant_id', 'pos_register_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('devices');
    }
};
